### PR TITLE
Graph lines update

### PR DESCRIPTION
**Pull request by sgober**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:
Removed the lines from all vitals & labs graphs by passing a flag in the metadata for each subsection.  Right now, this is showLines flag is always set to false, but it will allow us to show the line easily for some other subsection in the future rather easily. 

Due to a miscommunication, also added the ability to toggle between no line and line, but currently have this commented out.  Left it there in case it is ever wanted.  If you want to see how that works, uncomment line 200 in `BandedLineChartVisualizer.jsx`.

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
Nice @sgober ! 

I know that the toggle between showing and not showing the line on the UI is commented out but I tried it out and it looks cool! 

[NN1] Since there is no line now, can we make the points stand out more? Maybe fill in the point so that it has an inner fill as opposed to being hollow?

[NN2] When opening a note or closing a note (basically resizing the graphs), the dots take awhile to redraw which is a bit jarring. This appears in fluxnotes.org too so I am on the fence as to whether we should just make a jira for this but it's more obvious now that there is no line. When there is a line, the line remains on screen and is resized. The dots, however, completely disappear and take a long time to reappear. When we had both the line and dots, it was less noticeable that the dots were missing

[NN3] Demo1 now has no information in the lab graphs. I'm not sure if we are still using demo1 so if we aren't using that endpoint, I'm ok with this just being a jira

**Comment by gregquinn2001** [comment]
@sgober  can you explore NN1 and NN2? Maybe we can come up with a new approach to drawing the dots and address both at once? Or is it done by a 3rd party component and we have no control without modifying their code?

For NN3, demo1 should work.

**Comment by sgober** [comment]
@nicoleng12 @gregquinn2001 

[NN1] I worked with @Dtphelan1 on this and filling the dot made the graph look like an eyesore (see below for one of the examples).  We decided it was best to make the border on the dot a bit thicker to make it stand out more.  I could make it even thicker if you think that would help.  Also open to any other ideas.

Screen Shot 2019-03-20 at 11 48 43 AM

[NN2] The issue with this is that recharts automatically animates the drawing of the line (you can see this on disease status) and then all the dots show up at the same time.  I'm not sure there is a way around not having the chart animate the line even though it is hidden, since it is technically still a line chart.  I can look into it and see what I can do but no promises here

[NN3] I will look into this

**Comment by gregquinn2001** [comment]
@sgober  nice work on these! Don't spend too much more time on any of these. NN3 would be the priority in my mind, but only spend a little time looking into each one. Thanks!

**Comment by sgober** [comment]
[NN2] resolved

**Comment by gregquinn2001** [comment]
Awesome!

**Comment by gregquinn2001** [comment]
Let's not spend any more time on NN1. Dots look great and performance is great too so NN2 is definitely resolved! Although it was a feature (animation)! :) 

If you can address NN3, I think this is good!

**Comment by gregquinn2001** [comment]
NN3 works fine for me! ????

**Comment by sgober** [comment]
I am also seeing [NN3] work for me now.... maybe changing the animation fixed it?  However on `fluxnotes.org` there are only lines on demo 1, no dots.  Not sure why...

For [NN2], I only turned off the animation if the lines were hidden, so the feature is still there!

**Comment by nicoleng12** [comment]
I agree with Greg on NN1. Based on your explanation let's keep it the way it is.

NN2 is fixed. Works beautifully now! Thanks!

NN3 is no longer an issue for me... Perhaps the fix you made for NN2 somehow fixed it?

**Comment by sgober** [comment]
JIRA 1895 covers the dot issue on demo1

**Comment by gregquinn2001** [comment]
There is no dot issue! We don't need a jira! Please delete unless someone wants to convince me otherwise. They look fine! I agree that NN3 is resolved!

**Pull request merged**
