### PR TITLE
Allow insertion of all shortcuts based on triggers in metadata

### PR DESCRIPTION
**Pull request by danlee1025**
Addresses JIRA-2025.

- Removed trigger check to determine if a shortcut is currently valid.
- Updated `isComplete` functions for `SingleHashtagKeyword`, `CreatorBase`, and `CreatorChild` to require parent context.

Shortcomings:
- We can no longer autocomplete `#disease status` because `#disease` always gets inserted.  This was one of the issues we mentioned in our whiteboarding session and is a JIRA.
- Shortcuts are not updated when a parent context is finally inserted.  This will be fixed in JIRA-2026.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
-  Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
-  Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
-  Document any new APIs/extension points
-  Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by sgober** [comment]
[SO1]  I am seeing #toxicity and #staging update with a space after the word, but not when I press the enter button (remains #attribute without red underline)

**Comment by danlee1025** [comment]
For SO1, I think it makes sense to have a space after the word since we are using space to trigger the autoreplace.  Enter key doesn't trigger the autoreplace plugin but we do have a JIRA to have additional keys besides space to trigger the plugin.

**Comment by danlee1025** [comment]
I think the branch is up to date with `shortcut-entry-overhaul`.

**Comment by jafeltra** [comment]
[JA1] I think creator intermediary shortcuts will need support for this as well. Typing "#as of " gives me an error: Uncaught TypeError: Cannot read property 'getAttributeValue' of undefined.

Also, I noticed a bug on shortcut-entry-overhaul, which I made into a Jira (see: ASCODCP-2044). It's related to selecting multiple shortcuts and deleting.

**Comment by sgober** [comment]
Sorry @daniellee1025, I was looking at `shortcut-entry-overhaul` not being rebased with `master`.

I can also confirm JA1.

**Pull request merged**
