### PR TITLE
Highlight tdp results

### PR DESCRIPTION
**Pull request by mgramigna**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Jira 1389: Highlighting search results in the targeted data panel. 

* Search results in the targeted data panel now receive highlight in addition to scrolling
* Examples include
    * Section and subsection names
    * Keys or values in tabular view
    * Structured data in narrative view
    * Points on the lab graphs or disease status graphs
    * Data in the medications section
    * Didn't highlight any actual data in the timeline or treatment options because I'm not sure we even need to. Any thoughts?
* There is now a debounce on the search results to limit the amount of re-rendering that the targeted data panel does: new search results wait to be fetched until at least 500ms after the last time they were fetched.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks good! I'm not sure what you would highlight in the treatment options section, but for the timeline, it seems like a highlight might be helpful if you highlighted the item that matched the search result. It seems like this would be in line with the lab results graph. Is there another reason why it wouldn't make sense to highlight on the timeline? Also a few other things I noticed:

[JA1] If all the results are highlighted to start with, should there be a different highlight color to show you which is currently selected in the search results dropdown? Also I noticed that the notes that contain a search result are not highlighted until you select a result from the dropdown. Maybe instead the targeted data panel results should do something similar and only highlight when the result is selected?
[JA2] Zooming in on the timeline and then searching for something resets the timeline zoom. I don't believe this happened before, but I could be wrong.

**Comment by nicoleng12** [comment]
This is pretty cool! Nice job @mgramigna 

[NN1] - When I do a search on "surgery", the top two options highlight the same thing on the targeted data panel. This is a little confusing. I think it's related to JA3 but the procedures section only has one view (just the tabular view)

image

**Comment by nicoleng12** [comment]
The app currently doesn't run in IE due to a but that was fixed in master. Rebasing this branch should fix this.

**Comment by mgramigna** [comment]
Rebased. Looking into the comments now. Thanks Julia and Nicole!

**Comment by mgramigna** [comment]
Resvoled JA2

**Comment by nicoleng12** [comment]
[NN2] - The rebase did not fix the IE issue.  Turns out the issue is in a third party library used for the highlighting:
image

image

**Comment by mgramigna** [comment]
Resolved JA3

**Comment by mgramigna** [comment]
Resolved NN1

**Comment by mgramigna** [comment]
Resolved NN2. I no longer use that module and instead forked the elasticlunr repo to do the field comparison we need and made package.json point to my forked copy

**Comment by mgramigna** [comment]
Fixed JA-rambling: I added functionality to highlight data on the timeline to

**Comment by mgramigna** [comment]
After talking with Greg I made two Jiras to address concerns for JA1 😢

**Comment by jafeltra** [comment]
Nice job with all the fixes! The timeline highlights look really cool! JA2 and JA3 are fixed. The Jiras made will address JA1. I'll let Nicole confirm the fixes for the NN's, but they look good to me as well.

**Comment by nicoleng12** [comment]
The fixes for the NN's look good. The app works again in IE

**Pull request merged**
