### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 1811

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [X] Branch implements task as expected
- [X] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [X] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [X] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [X] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [X] Document any new APIs/extension points
- [X] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [X] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [X] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by mgramigna** [comment]
[MG1] Not quite related to the security vulnerabilities, but since this PR deals with dependencies, I'd say it might be relevant enough to remove `package-lock.json` as part of this. This really should not be in our repository at all since we are using `yarn` and `yarn.lock` to control our versions.

**Comment by Dtphelan1** [comment]
Seconding MG's comment. I think we only added the package.json file accidentally when someone node installed instead of yarn installing.

**Comment by Dtphelan1** [comment]
That said, this all looks good to me otherwise. Once we resolve that thread, I'll approve.

**Comment by Dtphelan1** [comment]
Rebased

**Comment by gregquinn2001** [comment]
MG1 resolved.

**Comment by Dtphelan1** [comment]
Tested that the app loads and that I can run `yarn build`. All checks out on my end! Looks good to me 👍

**Pull request merged**
