### PR TITLE
Set up MCODE Pilot Section Headers

### PR DESCRIPTION
**Pull request by noranda**
This PR sets up the `/cpp` endpoint to start implementation of the new MCODE Pilot designs. Includes placeholders for future work.

- Created a new `mcode-pilot` folder to house components
- Created treatment options visualizer and selector components
- Set up and styled treatment options headers including titles, subtitles, and subheaders which are expandable

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
Looks great Noranda! This works in IE and in Chrome, looks fine in IPad pro mode, and the backend tests pass. This PR successfully addresses jira 1595. 

Should "excluded criteria" be all the same style? Right now "excluded" is bold and italicized while "criteria" is normal.

[NN1] - Really small comment. Can you put the generated css from sass in git ignore (TreatmentOptionsSelector.css and TreatmentOptionsVisualizer.css)? This is temporary and eventually we can put all css files in git ignore. But for now, since not all of our styling has been converted to sass, we have to ignore specific css files. 

This branch needs to be rebased.

**Comment by gregquinn2001** [comment]
I fixed FN targeted data panel infra so that new treatment options section name gets indexed correctly. Also renamed MCODE Pilot to remove hyphen from MCODE name

**Comment by gregquinn2001** [comment]
This looks good otherwise. good start. I'm a little disappointed that the filtering support at the top won't use the general filtering infrastructure we had in place. Also, I'm assuming this new visualizer will accept exactly the same data format for now. We can adjust that as we learn more, but for now let's keep that the same. In that case, we can use the same data type though - ClusterPoints. We can rename the data type if we want but both visualizers should use the same input data

**Comment by noranda** [comment]
Added CSS files to gitignore, added mockup to JIRA task (which does show styling as implemented), and rebased.

**Comment by nicoleng12** [comment]
All my comments have been addressed, thanks! Once GQ1 is addressed I'll approve this

**Comment by gregquinn2001** [comment]
@noranda , if you want to discuss GQ1 further let me know - especially if you have other thoughts on it!

**Comment by gregquinn2001** [comment]
We are going to hold off on GQ1 for now. @noranda and I spoke today. Before we start adding the data into the viz, we will meet and discuss our preferred approach. We want to wait until just before because we feel like the viz requirements are still changing based on CancerLinQ data availability and clinician feedback. Changing a lot now may not be that productive.

**Pull request merged**
