### PR TITLE
Treatment options visualization

### PR DESCRIPTION
**Pull request by karenzheung**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Jira 1220 
Do yarn install to get the highcharts module
Scroll to bottom of target data panel to view the current static version of the treatment option visualization. 

Note: Chart does not properly resize when a note is open 

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [n/a] Cheat sheet is updated
- [n/a] Demo script is updated 
- [n/a] Documentation on Wiki has been updated 
- [n/a] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [n/a] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] labelling for 2nd x axis at the top overlaps the top line of the chart.

**Comment by gregquinn2001** [comment]
[GQ2] Line 201 of ScatterPlotVisualizer has a console.log on it still.

**Comment by karenzheung** [comment]
Removed the console.log statements and fixed the second x axis overlapping grid

**Comment by gregquinn2001** [comment]
[GQ3] Let's add treatment options visualization to sarcoma summary as well. I can help!

**Comment by karenzheung** [comment]
Added treatment options to pilot1 summary

**Comment by danlee1025** [comment]
Branch needs to be rebased.

**Comment by gregquinn2001** [comment]
Karen just rebased so ready for merge when final approval!

**Comment by danlee1025** [comment]
I see a lot of variable declarations with `var`.  Can we change the code to use `const` and `let` to remain consistent?  These declarations are in `ScatterPlotVisualizer.jsx` and `SummaryMetadata.jsx`.

**Comment by karenzheung** [comment]
Replaced the var declarations

**Pull request merged**
