### PR TITLE
Imported new ES6 classes with toFHIR methods.

### PR DESCRIPTION
**Pull request by danlee1025**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Addresses JIRA-1291.

- Imported new ES6 classes provided by Mike O'Keefe.  
- Added JIRA to update entries in hardcoded patient data.
- Tested toFHIR functions and reported bugs to Mike and Chris Moesel.

No changes should have been made to the app.  Just test that app is working like normal with updated ES6 classes.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
-  Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

-  Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
-  Use public class field syntax for binding functions - ex. handleChange = () => { ... };
-  Code is commented

**Tests**

- [x] Existing tests passed
-  Added Enzyme-UI tests for slim mode 
-  Added Enzyme-UI tests for full mode
-  Added backend tests for new functionality added
-  Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks good to me! I realize this is a little late, but I went back to see if I wrote down differences the last time I updated the ES6 classes and realized I made this wiki page: https://github.com/FluxNotes/flux/wiki/Updating-Generated-ES6-classes. Sorry for not thinking to do that earlier. There isn't much in there besides the SourceClinicalNote info though, so this looks good to me! I wasn't exactly sure how/if it was needed to test the toFhir methods, but I tested the app and everything seems to be working as expected!

**Comment by gregquinn2001** [comment]
This does look good. I just have one small thing
[GQ1] Could you delete the cimi package under model? We don't use that. We use shr only.

**Comment by jafeltra** [comment]
I also realized I think this needs to be rebased.

**Comment by danlee1025** [comment]
Rebased and removed cimi directory.

**Pull request merged**
