### PR TITLE
Highlighted search suggestion

### PR DESCRIPTION
**Pull request by Dtphelan1**
Addresses ASCO-DCP 1518: [Pilot 1] Add separate color for highlighted search results that are selected from the search dropdown.

Now when you hover over or arrow-down over a particular search match, that search match in particular will be styled differently in addition to the typical highlighted styling. Places to check are: 
- Notes listed in our notes-assistant
- Structured phrases in a note 
- Text in a note
- Section headings 
- Banded line chart viz: data Points 
- DiseaseProgression viz: data points
- Narrative visualizer
- Tabular viz: Data value and data-element name
- Timeline: bands of events and points of events

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [ ] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
Nice coloring!

[NN1] - When I do a search on "follow-up", the search results show the notes that are of type follow-up and in the note content is uses the bracket notation for representing condition. When displaying note content for other data, it seems fine (no brackets). It's just the condition

image

When I do the same search on fluxnotes.org or in master, there is no bracket around the condition in the search results

**Comment by danlee1025** [comment]
This was fixed in `master` so when this branch gets rebased it should get fixed.

**Comment by Dtphelan1** [comment]
Rebasing now, thanks for that Dan

**Comment by nicoleng12** [comment]
[NN1] Highlighting in narrative view is not working. When I switch the summary section in the targeted data panel to narrative mode, the i search on "gastro...." and hover over it in the search results, "gastro..." is not highlighted in the summary section in the targeted data panel

**Comment by Dtphelan1** [comment]
DP1 - Search gives all plain-text content matches the special highlighting when any one is hovered. 
To Reproduce: 
1. Open first note;
2. Type 'follow';
3. Hover over first suggestion; 
See that all instances of the term 'follow-up' are highlighted as if hovered, even though it should only be one.

**Comment by nicoleng12** [comment]
Question for @mgramigna and @jafeltra It would be nice if when you search for an item that is on the timeline, that the timeline scrolls the selection into view so that users can see the highlight. I don't think that's within the scope of this PR so I would be ok if this was made into a jira

**Comment by Dtphelan1** [comment]
Fixed DP1 and a unlisted DP2 - the separate definitions we have for the various remove-formating-from-text functions led to a difference in expected behavior; this manifested itself by highlighting the wrong text in the searchSuggestion dropdown when searching notes with conditions (e.g. the first one). 

I'm making a jira to create a utility fn that does this across the board since it's already shown up as an issue; sadly I did  not have the time to do this before having to leave for my flight. 
🛫 💻 🛬

**Comment by nicoleng12** [comment]
Everything looks good! All the issues raised have been addressed. This looks good in IE and in chrome. Back end tests pass

**Comment by nicoleng12** [comment]
Rebased

**Pull request merged**
