### PR TITLE
Align Cancer-Summary Section with mCODE Data

### PR DESCRIPTION
**Pull request by Dtphelan1**
This PR endeavors to capture any top-level entries defined in mCODE 0.5 (link to IG can be found on Slack #shr-flux) missing from the cancer summary section of our `GeneralCancerSummarySection`, and to align the language used in our `GeneralCancerSummarySection` with the terms in the IG. Key changes that can be seen on /ccp from the UI perspective include: 

- Add Clinical Status to the cancer summary section.
- Sxparate subsection for Stage, including a K-V pair for Clinical Stage as well as Pathologic Stage
- Add Disease Status to `GeneralCancerSummarySection`, specifically add a new subsection for disease status with slight changes in the language used for labels (compared with /demo2. Since they're under the Disease Status subsection, I've changed 'Disease Status' to 'Most Recent Disease Status').
- Displaying TNM values after the stage group.
- Updating language in the Performance subsection; changing Kanofsky and ECOG from "Panel" to "Status"
- Update language from "Tumor Histology" to "Histological Type"

Changes to the model include:
- Adding a FluxTumorMarker wrapper. 
- Making FluxEstrogenReceptorStatus , FluxProgesteroneReceptorStatus and FluxHER2ReceptorStatus  extend the FluxTumorMarker wrapper.
- Adding a FluxTNMStagePanelMember wrapper.
- Making FluxTNMClinicalDistantMetastasesClassification, FluxTNMClinicalPrimaryTumorClassification, and FluxTNMClinicalRegionalNodesClassification extend the FluxTNMStagePanelMember wrapper.
- Defining how to get stageComponents (i.e. TNM and other used values as defined by a particular cancer) on the FluxTNMStageGroup wrapper.
- Adding a function to getMostRecentTumorMarkers onto the FluxSolidTumorCancer wrapper.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [x] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [x] Document any new APIs/extension points
- [x] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] TNM values should be in parenthesis after stage

**Comment by gregquinn2001** [comment]
[GQ2] We should get rid of FluxEstrogenReceptorStatus and FluxProgesteroneReceptorStatus. It looks like HER2 class is already gone. We should only have FluxTumorMarker I  think now. Not sure what the brca ones are but they don't extend TumorMarker so there's an issue with the model in my opinion there. I'd focus on oncocore representation. oncocore can use shro but not vice versa I believe.

**Comment by gregquinn2001** [comment]
[GQ3] I think the subsection Disease Status in the general cancer summary should be called most recent disease status and then the name of the first name/value pair in the subsection should be status,

**Comment by gregquinn2001** [comment]
[GQ4] Let's make a subsection in the general cancer summary section called "Tumor Markers" and then create a name value pair for each tumor marker found and then we can do isUnsigned for each one individually.

**Comment by gregquinn2001** [comment]
[GQ5] This may be my fault but I don't think the performance scores should be on the condition but instead on the patient and therefore are patient-level values. Maybe they should be pulled out into their own subsection because they are patient-level as well.

**Comment by gregquinn2001** [comment]
[GQ6] Can we implement the genes? Does our test patient Jane have BRCA1 or BRCA2? Perhaps mCODE model isn't mature enough in the genetic area?

**Comment by Dtphelan1** [comment]
[GQ1] - Done ✔️ 
[GQ2] - Right now those classes still provide us information on the abbreviated names. HER2 is still present as well; I think the name got changed a while ago from the full "HumanEpidermal..." to "HER2" in the model. Will talk to you about suggestions re: how to get that info without wrapped on Slack.
[GQ3] - Done ✔️ 
[GQ4] - Done ✔️ 
[GQ5] - Can do, will chat on Slack regarding specifics.
[GQ6] - Neither in 0.5 nor 0.6 does mCODE offer a representation of geneticMarkers. As it stands today we simply extend FluxObservation with FluxBRCA1Variant (for example). Because of the lack of base class, I don't think I'd immediately be able to have a GeneticMarkers section in the same way we have for Tumor Markers. I _can_ try to look for panels if we'd like, but I don't think any of our patients actually have genetic panels in our backend. Again, I could try to add that as well. Open to discussion.

**Comment by Dtphelan1** [comment]
Made a pass at getting rid of specific receptors from our FNObjectModel. The result was... intense, but effective. We no longer use those speicifc receptors in our object model. That said as a product of this update a few other things have happened: 

- Created a version of our patient Jane in v0.5 of mCODE by copying the contents of our run-time mapped v0.1 patient into a new file. Have also removed v01 Jane from our code. 
- Created a new datasource to access this new Jane, `HardCodedMcodeV05DataSource.jsx`. 
- Currently I've removed the TumorMarkers Narrative Snippet, because I'm not sure how to use define the path to that data since it's generated dynamically through the itemsFunction. This is a glaring issue and I'm open to hearing suggestions as to how we should be solving it. 
- Had to give the ER/PR/HER2 shortcuts some way of specifying what kind of tumor marker they are. This is currently done by defining another setter in the `updatePatient` field. 

This should address [GQ2], which should mean all GQ's are addressed! 

You know what that means @gregquinn2001 -- get hunting for more bugs 👍

**Comment by gregquinn2001** [comment]
Do we handle the tumor marker conversion (from ER, PR, and HER2) in the v0.1 data source for the other patients?

**Comment by Dtphelan1** [comment]
I'm pretty sure we handle it -- I've updated the mapper to map those v0.1 classes to FluxTumorMarker in the FNOM. To test this I've tried making data on those endpoints, and have confirmed that loading patients on /demo2 loads those tumor markers appropriately

**Comment by mgramigna** [comment]
I think this looks good! Should we make a Jira for adding a tumor markers snippet to narrative view?

**Comment by mgramigna** [comment]
FYSA: I was testing setting the tumor marker values with hashtags on `/demo2`, and the "Open Source Note" functionality no longer works after writing the data with hashtags and signing the note. Went to master to check and the bug also happens on master so outside the scope of the PR I'm guessing.

I'll make a Jira

**Pull request merged**
