### PR TITLE
Added ROS section to targeted data panel

### PR DESCRIPTION
**Pull request by nicoleng12**
This PR addresses jira 1495. 

Added Review of Systems section to the targeted data panel. In addition to the questions/answers, the ROS section also displays the author and date. Changed the false/true answers to no/yes in the display to be more user friendly.

Updated tabular list visualizer to allow sections to override the isWide default display. For the ROS section, in order to make the author/date section be displayed on top of the questions/answers section, had to allow the section to override the default 2 column display when there are multiple subsections. 

Also added a new visualizer data type (NameValuePairsOnly) for the section to only have a tabular view option. Added a jira (https://jira.mitre.org/browse/ASCODCP-1522) to look into adding a narrative view for ROS data

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added Enzyme-UI tests for slim mode 
- N/A Added Enzyme-UI tests for full mode
- N/A Added backend tests for new functionality added
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] Let's sort the list of systems so that yes's come first then no's and within each of those, we sort alphabetically. In other words, we'd see headaches then rashes then the rest in alpha order

**Comment by gregquinn2001** [comment]
[GQ2] Also let's move this section down to below allergies as a starting position.

**Comment by gregquinn2001** [comment]
Overall pretty cool to see new sections being added using the new approach! Code looks great!

**Comment by nicoleng12** [comment]
Thanks for the great comments! I've address GQ1 GQ2

**Comment by gregquinn2001** [comment]
love the author's name BTW!!!!

**Comment by mgramigna** [comment]
[MG1] Add ROS to /pilot1np endpoint

**Comment by nicoleng12** [comment]
MG1 addressed

**Comment by mgramigna** [comment]
Looks good! Just needs a rebase

**Pull request merged**
