### PR TITLE
Fix tabular list visualizer

### PR DESCRIPTION
**Pull request by gregquinn2001**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

JIRA 1361. Cleaned up TabularListVisualizer to use a common format of an object per cell. All the source viewing options still work. all the visualizations including alternative ones seem to work still. Now if you search for Surgery you see Timeline and Procedures result. Dates also result in Procedures and Conditions showing up. Try '15 Mar'.

Tests don't pass until the subtask to fix them is done.

JIRA 1378. If you scroll timeline to the top in targeted data panel with no note open and then perform a search, the search results now completely render over the timeline component.

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
rebased to search-structured-data

**Comment by jafeltra** [comment]
[JA1] The "View Missing Criteria" action on Clinical Trials seems to be broken. Clicking on the action from the "Criteria Fit" column just shows the subsection with "none" displayed, even though it should have data in it. Clicking on the action from the "Name" column gives an error: "Cannot read property 'value' of undefined at ColumnsIndexer.js:26".

**Comment by jafeltra** [comment]
[JA2] The names in Name Value Pair visualizers seems to be underlined and have actions associated with them, but they didn't before (ex. uou can click on "Name" and "Laterality" from Summary now). Is that intentional?

**Comment by gregquinn2001** [comment]
Fixed JA1

**Comment by gregquinn2001** [comment]
JA2 fixed!

**Comment by gregquinn2001** [comment]
rebased

**Comment by mgramigna** [comment]
[MG1] Related to JA1. In clinical trials for Ihanos, clicking on "5 of 6" > "Missing Criteria" changes the subsection name of the table that appears below it to "Missing 5 of 6 Criteria" instead of being "Missing PATINA criteria" and no data shows up

**Comment by gregquinn2001** [comment]
MG1 fixed

**Comment by jafeltra** [comment]
Fixes look good to me!

**Pull request merged**
