### PR TITLE
Fixes reinitialization of data on an existing note

### PR DESCRIPTION
**Pull request by Dtphelan1**
Avoids the re-initialization of data on an existing notes, avoiding the case where data with no written as-of date uses the default date of "today" on load. Old instructions for reproducing: 

- Go to the pilot1 endpoint
- Note in the summary panel that disease status is "Stable, neither improving nor worsening". Note also in the disease progression line chart that there are 7 data points in the chart and the date of the latest data point is Aug 23
- Open the Aug 23 existing note
- At this point the targeted data panel has been updated. If you look under the summary section, disease status is now "Stable", without the extra string "neither improving nor worsening" indicating that this has been updated. Look at the disease progression line chart. The latest data point is now Oct 10, which has replaced the Aug 23 data point that we saw prior to opening the existing note

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by sgober** [comment]
[SO1] FullApp test 6.5 is failing

**Comment by Dtphelan1** [comment]
I have no idea what's happening here, but I can confirm that my changes are causing it. Anyone have any ideas here?

**Comment by mgramigna** [comment]
This likely isn't very helpful, but re-adding the initialize function for SingleHashtagKeyword makes the test back but obviously this also makes the bug come back

**Comment by Dtphelan1** [comment]
That's how I confirmed I was causing it 😫

**Comment by Dtphelan1** [comment]
Fixed SO1 but I don't know how I feel about the fix; I'll discuss at Standup. 👍

**Comment by jafeltra** [comment]
This looks good to me! I walked through the changes with Dylan and they all make sense to me! The tests pass as well. This just needs to be rebased.

**Pull request merged**
