### PR TITLE
Changed NLP-server domain to parser.mitre.org

### PR DESCRIPTION
**Pull request by Dtphelan1**
In addition, I've documented in detail the steps taken in provisioning and setting the NLP server. Look over this [documentation here:](https://github.com/FluxNotes/flux/wiki/NLP-Server%3A-Provisioning-and-Troubleshooting)

Happy testing!

### CODE REVIEW

**Comment by jafeltra** [comment]
This is really cool! I skimmed through your wiki page and it is really detailed. The only thing I noticed is that the gitlab link gave me a 404. I'm not sure if I just don't have the right permissions to view it though.

**Comment by Dtphelan1** [comment]
That's frustrating and almost 100% right. Don't know what we want to be best practice on that... I can make a comment saying if you can't read it you should reach out to me.   
  
  
  

  
  

  
  
>

**Comment by jafeltra** [comment]
That seems fine to me given that you are doing that in other places as well and you describe some of the steps after the link too!

**Comment by Dtphelan1** [comment]
Addressed your previous comment @jafeltra ! Let me know if there's anything else 👍

**Comment by jafeltra** [comment]
Looks good to me!

**Pull request merged**
