### PR TITLE
Replace side effect in CCP mock data

### PR DESCRIPTION
**Pull request by dehall**
Addresses ASCODCP-2110.

Removes "erectile dysfunction" as a side effect from female patients in the mock data set. 
For patients who were left with no side effects as a result, one was added back in based on their treatments. If they had surgery, their side effect was seroma. If they had chemotherapy, their side effect was fatigue. If they had radiation therapy, their side effect was weight loss. Finally if they had hormonal therapy, their side effect was fatigue. (I used a script so not all of those may be used in the resulting data)

Also replaces erectile dysfunction with dyspnea as a possible side effect in the mock data updater so that it doesn't get added back in unexpectedly.

Finally, it was confusing looking at both `mock-data.json` and`mock-data.js` (which was unused except for importing mock-data.json) so I deleted mock-data.js and updated references to it.

---

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by dehall** [comment]
Good catch, and that's an interesting point. I don't know how common it would be in practice but there are definitely other combinations of filters that will remove all instances of a side effect.  I'd suggest that be a new issue on jira.

**Comment by dreeves4321** [comment]
That is a good catch. From a usability and information standpoint, the dropdown should only show non-zero side effects.

**Comment by rdingwell** [comment]
@dehall I agree that this should be tracked as a separate task in Jira
@dreeves4321 you are correct that this will not be an issue with the CLQ service as it does not provide side effect outcomes and that column will be turned off

**Comment by dehall** [comment]
Ok I created ASCODCP-2116 for that display issue

**Pull request merged**
