### PR TITLE
Fixed the functionality of switching between completion portals

### PR DESCRIPTION
**Pull request by danlee1025**
Addresses JIRA-2227.

- Added a `setTimeout` in `openCompletionPortal` to possibly wait for another completion portal to close before opening.
   -  Although this may not be the best approach, with the way we have implemented the opening and closing of portals, we would have to add in some complicated logic to determine when to open and close portals so this approach may be better for our time and effort.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
-  Manually tested in IE/Safari (verify app loads and basic feature testing)
-  Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
-  Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
-  Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
-  Document any new APIs/extension points
-  Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by sgober** [comment]
[SO1] I'm seeing some weird behavior when clicking on #date... if you expand disease status then click back and forth between status, reason and date, the date competition component flashes but doesn't stay visible

**Comment by danlee1025** [comment]
Ok will look at SO1.

**Comment by karenzheung** [comment]
[KZ1] When i expand #toxicity and try to select values by clicking on the incomplete, it doesn't replaced the incomplete with the selected value. It works if i arrow key into it and select

**Comment by danlee1025** [comment]
SO1 and KZ1 should be fixed now.

**Pull request merged**
