### PR TITLE
Update react scripts

### PR DESCRIPTION
**Pull request by rdingwell**
This PR implements an update to the react-scripts package along with all other changes required for the update.  Many files have been modified for this update, most of which are to deal with syntactic changes required by the webpack configuration used under react-scripts.  Additionally, the tests directory has been moved to `src/__test__`, also required by the update to the react-scripts package. 

Due to the large number of changes required for this PR I would suggest that it be reviewed with the following thoughts in mind.  

1.  The PR is incorporated as is and development continues under the constraints imposed by react-scripts. 
2. The constraints imposed by react-scripts are too stringent and an alternative approach to updating which allows for modification of the rules.  Note that this does not include or exclude the incorporation of the PR.  Any of these approaches or similar are not dependent on whats been incorporated in the PR or prevent it's acceptance
    - ejecting   
    - forking react-scripts 
    - react-scripts-rewire
3. There is no need to update the package, reject PR.   Note this does not exclude option 2 

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Reached out to the AF project I knew about; they have not ejected their react app, and hadn't considered it to the best of my knowledge. 👎

**Comment by danlee1025** [comment]
`react-app-rewired` with `customize-cra` seems to expose the eslint configurations that we want.  `customize-cra` has a plugin called `useEslintRc` which allows us to use our own `.eslintrc` and `.eslintignore`.  The only downside is if we use this plugin it ignores the default eslint rules set by react so we need to define all the rules in our custom `.eslintrc`.

I don't know webpack very well so I'm not sure which config options we actually want exposed but `customize-cra` does seem to have a decent amount of webpack plugins.  @rdingwell Do you want to take a look at the [available plugins](https://github.com/arackaf/customize-cra#available-plugins) and see if those plugins expose enough?

@gregquinn2001 @rdingwell What should be our next steps?  Did we want to create a JIRA to incorporate `react-app-rewired`, `customize-cra`, and our custom `.eslintrc` or did we want to discuss further?

**Comment by danlee1025** [comment]
Incorporated `react-app-rewired` and `customize-cra` to expose `eslint`.  Our `.eslintrc` extends `create-react-app`'s `eslint` config and `.eslintignore` is now respected.  In the future we can easily add rules to our `.eslintrc`.

**Comment by sgober** [comment]
Nice work @daniellee1025! A couple of things I noticed...

1) the build definitely got slower, maybe like 2-3 times slower
2) I love that we have a linter now!  However there are a couple of linting errors I see when running `yarn lint` that should be fixed before merging
3) Can we hook the linter up to travis so we don't have to run it manually?

**Comment by danlee1025** [comment]
1. Yeah initial build is definitely slower but I think build gets a lot faster for subsequent builds.
2. Fixed
3. I'll look into this.

**Comment by jafeltra** [comment]
This looks great! I love the linter and new rules!

I did a fairly thorough review of the app since so many files changed. I found a few things:
expected `array`.
[JA1]: Pasting structured phrases gets an extra space after pasting. I'm not sure why but I can help look into this.
[JA2]: When I tried to open a source note from an unsigned stopped medication, I think I got stuck in an infinite loop. However, I can't seem to reproduce this so I may retract this JA2 after a bit more testing.

**Comment by jafeltra** [comment]
Well neither of the JAs are relevant anymore, so I think this looks good!

**Comment by jafeltra** [comment]
[JA1] FNE test 6.3 fails for me.

**Pull request merged**
