### PR TITLE
Treatment options gets data from mongodb

### PR DESCRIPTION
**Pull request by karenzheung**
JIRA 1222
getTreatmentData calls server which now implements mongodb. 
Note filtering criteria is still hardcoded. Only filtering on prostate cancer, because that is the only data we have. 
You will need the server and client
https://github.com/FluxNotes/treatment-options-javascript-client
https://github.com/FluxNotes/treatment-options-node-server

Detailed instructions on installing the api client package, running the server, and setting up mongodb can be there. 

In SummaryMetadata.jsx, if you edit line 1852 to be this:

const data = api.findTreatmentOptionsByPatientStats("prostate cancer");
or 
const data = api.findTreatmentOptionsByPatientStats("prostate cancer", {race: "Black"});

you should see that the chart displays a lot more points as there are less filtering criteria. 

When server or mongo is not running the section will display a "server unavailable" message. If no data is found for the criteria section will display "No relevant data found for patient" message. 

A JIRA has been created for each issue:
(1323)No indication of whether results are relevant or demo purpose only 
(1324) Should create demo data for patients
(1325) Server should handle more generic criteria on getting treatment data
(1326) Server url should be configurable for easier testing and use

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] let's add the code necessary to get actual criteria and use them and then disable it in favor of the hard-coded version.

**Comment by gregquinn2001** [comment]
[GQ2] We need to make sure all projects are using yarn instead of straight npm. The node server says to do an npm install. I did a yarn install and it seemed to work fine.

**Comment by gregquinn2001** [comment]
[GQ3] Server has some log messages still. Were they for debugging or should we keep them?

**Comment by gregquinn2001** [comment]
I updated the insertTreatmentData.js so it would run. I removed two const declarations at the top that weren't necessary. It wouldn't run because when you declare a const you have to initialize it and they weren't being initialized. After I did that, it ran and worked perfectly.

**Comment by gregquinn2001** [comment]
[GQ5] Security vulnerability from github:

  | FluxNotes/treatment-options-node-server
-- | --
Known high severity     security vulnerability detected in string <= 3.3.3 defined in package-lock.json. | Known high severity     security vulnerability detected in string <= 3.3.3 defined in package-lock.json.
Known high severity     security vulnerability detected in string <= 3.3.3 defined in package-lock.json.

**Comment by karenzheung** [comment]
Fixed GQ1 - GQ3

**Comment by gregquinn2001** [comment]
[GQ6] It looks like even though we are just passing condition code and race that the javascript client is including a grade of undefined in the REST GET request to the server resulting in no data.

**Comment by karenzheung** [comment]
Regarding [GQ6], I renamed the collection in the database from entries to treatment options data in both the MongoDataSource.js and insertTreatmentData.js. So when you pulled, the code was updated to look in treatment options data instead of entries. Rerunning node insertTreatmentData.js should fix the problem. I forgot to mention this, my bad!!

**Comment by gregquinn2001** [comment]
I think I did re-run insertTreatmentData but I'll try again! Thanks.

**Comment by gregquinn2001** [comment]
Nice I retract GQ6. It was my mistake. I didn't pull the latest for the server. Sorry!

**Comment by gregquinn2001** [comment]
For the security vulnerabilities, there's more information on github about them. If you view the details, it will tell you what version of what dependency to move to to resolve the issue. Let me know if you can't find them.

**Comment by karenzheung** [comment]
Fixed [GQ5] and [GQ4]
I think the security vulnerabilities issues came from the fact that the server was generated by swagger which was using swagger-tools. Swagger-tools version 0.10.1 had a dependency on string 3.3.3 and superagent 1.2.0 both of which had security vulnerabilities. Upgrading to swagger-tools ver 0.10.4 removed the string dependency and updated superagent to 3.5.2. Looking at the swagger-tools github project page, the most current version still has some issues with its dependencies.

**Comment by mgramigna** [comment]
Aside from me being a JavaScript stickler I think this looks really good! Should be all set for an early merge on Monday.

**Comment by karenzheung** [comment]
Fixed MG1 and rebased

**Comment by karenzheung** [comment]
rebased!

**Pull request merged**
