### PR TITLE
Newline structured data bug

### PR DESCRIPTION
**Pull request by sgober**
Added a scrollIntoView that fires anytime structured data is created in the editor.  This should only adjust the scrolling if the structured data dashed line is out of view, not in the middle of the editor.  Try adding structured data in all ways at the bottom of the note as well as in the middle of the note.

Potential shortfall:  the scrollIntoView options are not supported in Safari and I believe IE (see here: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).  The affect this has is if you add structured data to a line at the bottom of the editor but it is not the last line of the note (i.e. there are more lines hidden that will show if you scroll down), then the scroll that adjusts the view to see the dotted line does not place it at the bottom of the screen like it does in chrome, but it tries to scroll it as much to the center as possible.  I think this is a pretty rare situation and there is no issue in chrome, but let me know what you all think.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] Minor but can you spell out 'Element' in function and variable names? AnchorEl --> AnchorElement. I always try to avoid abbreviations except when the abbreviation is known more than the spelled out version.

**Comment by gregquinn2001** [comment]
It's a little jumpy on IE for me but it works still. It scrolls  what I typed up and then back down but the dashed underline is visible when it's done still. It's slow as well but that's a separate issue in JIRA. Once GQ1 is resolved I'm good. I'll just approve it now.

**Comment by sgober** [comment]
[GQ1] fixed!

@gregquinn2001 the scrollIntoView options are not supported in IE and Safari, which is why you are seeing it be a little jumpy.  scrollIntoView by default tries to put the element in the center, which is why it scrolls up.  I don't really see a way around this if the anchorElement isn't the last element in the editor besides not doing anything.

**Comment by gregquinn2001** [comment]
Sounds good @sgober ! I was just confirming your pull request description! I'm trying to be better about testing in IE. I'm learning from @nicoleng12 !

**Comment by Dtphelan1** [comment]
.... I don't think it's working perfectly on my end.

**Comment by sgober** [comment]
@Dtphelan1 in what way?

**Comment by Dtphelan1** [comment]
This is what I do on my end, on `/pilot1`
1. Open a new note
2. Insert a template (e.g. Follow-up)
3. Select 'Gastro...' and click OK
4. Type '#di', selecting 'disease status' from the dropdown via arrow-clicks
5. Copy '#disease status'
6. Type enter and paste disease status
7. Copy two lines of disease status 
8. Type Enter and paste two lines of disease status

The auto-scroll doesn't always account for all of the copied text on my machine. If it does account for the first paste, additional pastes usually fail to scroll the complete amount sooner rather than later. (e.g. within 1-3 more pastes)

This also happens if instead of copying redundant information you copy and paste additional plain text above disease status (e.g. PLAN and other parts of the above template). I think this is a more compelling error case.

**Comment by sgober** [comment]
@Dtphelan1 I see that as well, when pasting more than one line.  I will take a look at it tomorrow

**Comment by Dtphelan1** [comment]
Soudns good 👍

**Comment by sgober** [comment]
The problem is that on paste the anchor element isn't being set correctly.  It is being set as the first line of what is being pasted, not the last where the cursor ends up after the paste.  I'm looking into a way around this but I'm afraid I'll break some other code along the way.

**Comment by sgober** [comment]
@Dtphelan1 [DP1] resolved!

**Pull request merged**
