### PR TITLE
adding mapper to mcode data source 

### PR DESCRIPTION
**Pull request by rdingwell**
Very simple PR to add the FHIR mapper into the mCODE data source.  This allows for patients that do not have mCODE profiled resources to be loaded into the application without it crashing.  The mapper currently just goes through all resources from the server and adds appropriate shr profiles to them so the underlying es6 class will import them correctly in the fromFHIR calls. 

## Submitter:

**Running the Application**

- [ ] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [ ] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by mgramigna** [comment]
Per discussion, +1 to what Dylan said. I think there's still some work that can be done to improve how this whole data source/mapping to mCODE works, but given what we have I think it makes sense to change the DataSrouce of `/smartcompass` to be the Generic DSTU2 SoF one.

The assumption of the `McodeV05SmartOnFhirDataSource` is that it takes mCODE v0.5 as input and outputs FN Object Model. For now, I don't think we should break that assumption

**Comment by gregquinn2001** [comment]
+1 as well! That was the original idea of the 2 different data sources!

**Comment by rdingwell** [comment]
That is a possibility.   I did not work on either of those so was unclear as to the differences and why there was a mapper in one and not the other

**Comment by Dtphelan1** [comment]
I've made the changes to use the other DataSource @rdingwell I hope that's alright. Going to review as best as I can now that that's changes.

**Comment by Dtphelan1** [comment]
This looks good to me now.

**Comment by dehall** [comment]
So this loads patients and seems to apply the profiles, but for some reason `/smartcompass` no longer uses the cancer condition template, it only uses the basic template. Ex, on master, load Marshawn McOde05 from moonshot-dev, the condition "Malignant tumor of colon" displays with the cancer template correctly via `/launchsynthea` and `/launchcompass`. Now on this branch, it still displays correctly via `/launchsynthea` but via `/launchcompass` it only shows the basic condition template. Not sure why that would have changed.

**Comment by dehall** [comment]
Another thought: since we know that the `mapper` is going to have to change in every deployed instance of Compass anyway, is this really necessary? I.e., the syntheaToV05 mapper is never going to be the actual mapper used, so rather than fiddle with this now and then change it again later, why not just wait until later and set the right mappers when we have them?
(That said I'm still curious about why the templates aren't working as expected so I'd still look into that)

**Comment by rdingwell** [comment]
I actually question the need for there to be 2 distinct data sources as the generic one is derived from mcodev05 one.   The only difference in functionality is the inclusion of a mapping ability.  The mCODE05 functionality as is could then be had by just not including a mapper in the generic class.  I would suggest that we merge this in to a single datasource.

**Comment by Dtphelan1** [comment]
Do we want to do that as a part of this PR? Also, I think the problems with regular conditions being viewed as cancer conditions in terms of the sections shown is a problem on `master` not just this branch. If true, we should make a separate ticket to investigate.

**Comment by Dtphelan1** [comment]
Alright, here's the scoop: 

Regarding the difference in sections, Dylan Hall, Matt and I determined this morning that the synthea mapper doesn't seem to be mapping cancers to FluxCancerDisorderPresent properly. This bug wasn't noticed on the /launchSynthea endpoint because that endpoint uses metadata on every condition that looks like the cancer-specific metadata for /launchcompass. I'll make a task to fix the mapper for cancers appropriately. 

Regarding the two dataSources, there's a discussion to be had that maybe we can have today in lieu of standup (since that's been cancelled)? @rdingwell let us know if that works for you.

**Comment by Dtphelan1** [comment]
Feels like this PR is being held up by the Datasource discussion still - @rdingwell or @dehall do you have additional thoughts?

**Comment by Dtphelan1** [comment]
Closing this for now. We can address questions about the generic vs. specific inheritence ordering and update the mapper to the v09 mapper when we have one.

**Pull request closed without merging**
