### PR TITLE
Added Most Recent Visit subsection to Summary

### PR DESCRIPTION
**Pull request by danlee1025**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This PR addresses JIRA-1313.

- Added ExpectedPerformer and ServiceProvider properties to two EncounterRequested entries.
- Subsection shows:
    - `Date of Last Visit` with currently logged user.
    - `Date of Last Visit` at ServiceProvider.
    - `Who Last Visited` at ServiceProvider.
- Changed loginUser prop from string(name of user) to userProfile object to pass user information down the app.

- Will make sure these changes don't affect the realism of the sarcoma patient update task that will be merged in another PR.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
-  Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

-  Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
-  Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added Enzyme-UI tests for slim mode 
-  Added Enzyme-UI tests for full mode
-  Added backend tests for new functionality added
-  Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] In the value FN we define in SummaryMetadata (lines 350ish) we should be using the mostRecentEnounter we've isolated as the second arg to this.determineSource, not the current condition. In order for this to work, we will probably also need to update this.determineSource  to be able to parse the source information from the encounter object. Not 100% sure though.

**Comment by jafeltra** [comment]
This looks good to me! The only thing I found a little confusing is that it now says the patient last visited with Dr. X123 on Sept 4, even though the encounter was only requested on that date, the patient didn't actually see the doctor then. Besides that one initial confusion, it looks good to me!

**Comment by danlee1025** [comment]
DP1 should be addressed.

**Comment by danlee1025** [comment]
Julia, currently we have an issue with `EncounterRequested` vs `EncounterPerformed` but it looks like it will be resolved with the newest SHR changes.  They have just `Encounter`.

**Comment by jafeltra** [comment]
Sounds good! Thanks for the explanation Dan!

**Pull request merged**
