### PR TITLE
Fixed first 2 columns using double table

### PR DESCRIPTION
**Pull request by ashih2018**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

- Fixed the first columns of the longitudinal table by creating two separate, side by side tables such that the information on the left can always be seen while the data collected on the right is scrollable. 

- The table on the left contains information of each of the sections(starred, name, date) 

- The table on the right contains data of the sections collected on each date. 

Potential bugs:

- When the window is small enough and/or when a note is opened on a small enough window size, either the lab data(table on the right) cannot be seen or the scroll bar is too small to be scrolled such that the lab data collected cannot be seen. This also happens sometimes in iPad mode when a note is opened.

- Right now min-width of each cell is hard-coded to 60px while there is no max width so cells can be very wide, especially if the lab name is very long. We will likely need to change this later.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [X] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [X] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [X] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [X] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [X] Code is commented

**Tests**

- [x] Existing tests passed
- [x] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by sgober** [comment]
Looks good Alex!  I have one tiny styling complaint...

[SO1] the right side of the table does not line up with the toggle icons like it does in other subsections (see screenshot below).  It looks like adding a padding-right of 10px should do the trick (see second screenshot)

Screen Shot 2019-06-21 at 8 36 55 AM
Screen Shot 2019-06-21 at 8 37 34 AM

**Comment by sgober** [comment]
test

**Comment by dreeves4321** [comment]
regarding [SO1], that's something that needs fixing across the board, with some standard approach (better than adding a little bit of padding here, and a little padding there). I'll add that to my list for my next styling pass which should be next week.

**Comment by mgramigna** [comment]
Thanks @dreeves4321!

I think that means we should maybe hold off on changing things related to that in the scope of this PR @sgober?

**Comment by sgober** [comment]
@mgramigna seems reasonable to me

**Pull request merged**
