### PR TITLE
Signed Styling Fix

### PR DESCRIPTION
**Pull request by Dtphelan1**
Straightforward fix here. Move some SASS around to make more sense in terms of the cascading nature of the styles. Differentiates the styling of creator structured fields in signed notes vs. in progress notes. 

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by dreeves4321** [comment]
It looks good, but this might be a good chance to change the editor to our designs. Otherwise, I'll make that a separate task for myself. 

Root: Open-Sans, $size-editor (which is new, =14px, .875rem), $weight-normal.
'bold' -> $weight-semibold
-incomplete -> solid 

I suppose there may have been strong feeling that the editor remain in serif, but I find it weird that it's so different.

**Comment by Dtphelan1** [comment]
Could you elaborate a bit on the solid comment? The other changes are pretty straightforwaard and would be no effort to roll into this. :)

**Comment by dreeves4321** [comment]
The incomplete elements have a dashed underline. In designs, it's solid, as in the TDP.
But I'm not adamant there. If we want ti dashed, that's okay, but I think solid is a little stronger and says, "you have to fix this!"

**Comment by dreeves4321** [comment]
Also, I'm happy to make those smaller fixes as "suggestions" right in the github interface. I'm just not sure how to do that...

**Comment by KeeyanGhoreshi** [comment]
Screen Shot 2019-07-03 at 10 12 39 AM

**Comment by Dtphelan1** [comment]
If the designs for solid v. dashed you're referring to [are these](https://github.com/standardhealth/shr_design/blob/master/Flux%20Notes/screen_designs/shr_fluxnotes_concepts_v16.2.pdf) I think this isn't 100% accurate since the in-progress structured phrase also has a solid underline. I'm going to leave it dashed for now since our philosophy until now has been dashed === in-progress, but if we want to reevaluate I'd be happy to chat later.

**Comment by Dtphelan1** [comment]
I've pushed the additional style changes and below is a snapshot. If this is too jarring of a change to be shoehorned into this PR, I'd love feedback saying so. If that's the case, we can just have a separate discussion at a late time re: the Root style changes. 
image

**Comment by mgramigna** [comment]
I personally don't find it too jarring. I think it looks good. Worth noting that this won't be going into `master` for a while

**Comment by Dtphelan1** [comment]
We'll merge this once we get @dreeves4321 's thoughts

**Comment by dreeves4321** [comment]
Looks great!
Yeah, it's not really fair for me to use my mockups as a standard for underlining. I've been pretty lax about it because it's a total pain to do that finicky work with the lines. And yeah, there is absolutely sense to keeping underlined.

**Comment by Dtphelan1** [comment]
Cool so this all looks good to you @dreeves4321 ? If so I'll merge away!

**Pull request merged**
