### PR TITLE
rename ccp app class

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Just some refactoring, changes the `CoreCancerPilotApp` class to `CompassApp`.  I wasn't sure if other Core Cancer Pilot classes needed to be changed as well, like `CoreCancerPilotSummaryMetadata` into `CompassSummaryMetadata`.  If that's what is needed than it will be a bit more refactoring.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [ ] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by mgramigna** [comment]
Looks good. This might be more of a question for @gregquinn2001: With the app being renamed, we still have some "CoreCancerPilotX" files in the app, such as `CoreCancerPilotDashboard` and `CoreCancerPilotMetadata`. Should these be renamed to Compass as well? Or are they fine as is?

**Comment by gregquinn2001** [comment]
[MG1] Yes, let's rename the other files as well.

**Comment by mgramigna** [comment]
One last thing.. should we change the actual endpoints for the app to `/compass` and `/compass2` instead of `/ccp` and `/ccp2`?

**Comment by Dtphelan1** [comment]
I think that’s a great idea personally.   
  

  
  

  
  
>

**Comment by gregquinn2001** [comment]
Well the real compass endpoint will be launched from the SMART on FHIR so it doesn't exist yet.

**Comment by Dtphelan1** [comment]
[DP1] Last thing I could find was the use of "core-cancer-pilot" as an ID tag in `compassAppDashboard`

**Comment by Dtphelan1** [comment]
Once that's done I think I'm good to approve.

**Comment by Dtphelan1** [comment]
This looks good to me now! Rebasing then merging.

**Pull request merged**
