### PR TITLE
Update context insertion to properly reflect location in editor

### PR DESCRIPTION
**Pull request by mgramigna**
See [Jira 1850](https://jira.mitre.org/browse/ASCODCP-1850) for screenshots of the original bug. When a context was added at the beginning of the note, it would still appear last in the active context breadcrumb. This was due to the implementation of `addShortcutToContext` incorrectly detecting where to splice the context.

I changed the implementation to allow for two possible options for knowing where to insert the context:

1) There is now a property on `Context` objects called `initialContextPosition` that specifies where to splice it relative to other contexts
2) Make a call to `FluxNotesEditor` to get all the context shortcuts before the cursor position, and splice in the new context after those

These are the following ways to add context to a note (I think I got them all):

* Typing the shortcut
    * Hitting enter or clicking on portal suggestion
    * Typing out the full shortcut without clicking/enter
* Inserting a context from the TDP into a note
* Pasting a context into a note
* Loading a close in-progress note
* Inserting a template that has context shortcute
* Inserting a context from the context tray
* Flux commands for inserting structured phrases

All of these cases should result in the context being inserted in the correct position, which will be seen in the active context breadcrumb.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks good! I came across two things. We can evaluate if either are something we want to actually fix now.

[JA1] Inserting the "test" template sets the context correct. However, if I add #staging from the context tray at the bottom of the note, the order of the contexts is wrong. It has context as "GIST, staging, Fracture."

[JA2] When using the "test" template, I've been getting the error at the bottom of the editor saying "GIST cannot be deleted because oncohist depends on it" quite often as soon as I try to type right after inserting the template. I don't know if this is related to context ordering or not. I can sometimes get it to happen on fluxnotes.org too. It doesn't seem to matter what order I add the conditions in the template because I've gotten it for both cases. However, I don't get it every time I add the template and I haven't figured out when I do and when I don't. (Sorry I don't have a better way to replicate yet.)

**Comment by Dtphelan1** [comment]
[DP1] Weird case, also to do with templates: If I have local contexts in the editor before I insert a template, after I finish inserting the template they won't appropriately be calculated as a part of context _until_ I close and reopen the note.

**Comment by Dtphelan1** [comment]
N.B. DP1 also happens on Master

**Comment by mgramigna** [comment]
Looking into JA1 now

Per JA2, there seems to be a bug where the GIST shortcut will stay bolded in the template even after it is selected/the template is inserted. In the case where it's bolded like this, that is when the error shows up. Hard to replicate, but the same behavior is on fnorg. I think it has to do with how quickly you slide the mouse down to the OK button for the test template...

**Comment by jafeltra** [comment]
Thanks for the update on JA2. I didn't realize that's what was happening. I think you're good to ignore JA2 in that case.

**Comment by mgramigna** [comment]
Resolved JA1 and DL1. 

Let's maybe hold off on JA2 for now, especially considering that template insertion might be getting an overhaul during the 13 pointer.

**Comment by gregquinn2001** [comment]
How are we ruling JA2 out of scope? It sounds like it is related to the context issue you were solving???

**Comment by mgramigna** [comment]
@gregquinn2001 It's a consequence of the bug where the mouse out event may sometimes not trigger properly if you move your mouse too quickly to the OK button when inserting the "test" template.

**Comment by gregquinn2001** [comment]
Ok. Sounds good then. The OK button will definitely be gone with the new note flow changes so the bug should be gone with it it sounds like.

**Comment by Dtphelan1** [comment]
DP1 is addressed! Just giving a once over before approving! 👍

**Comment by Dtphelan1** [comment]
Looks good to me! 😄

**Pull request merged**
