### PR TITLE
Fix copying and pasting into inserter shortcuts

### PR DESCRIPTION
**Pull request by danlee1025**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

Addresses JIRA-1747.

- Separates out logic to split up an inserter shortcut into a separate function called `splitInserterAndInsertText` so that it can be used by both `onKeyDown` and `onPaste`.
-  `onPaste` now recognizes when text is being pasted into an inserter shortcut and calls the `splitInserterAndInsertText` function.

To test:
- Copy and paste text into an inserter shortcut.  Plain text should now be inserted in between the structured field instead of grey text.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [x] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [x] Document any new APIs/extension points
- [x] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
My only comment would be "Can we think of a slightly more descriptive function name for the splitter?" This might sound stupid, but I didn't know that split function also inserted the plainText until looking at the function-block.

**Comment by Dtphelan1** [comment]
[DP1] Pasting structured fields inbetween oncohist results in them being inserted as plain text. Copy Gastro... and try to paste it anywhere in the oncohist.

**Comment by danlee1025** [comment]
@Dtphelan1 How about `splitInserterAndInsertText`?

**Comment by Dtphelan1** [comment]
I love it @danlee1025

**Comment by danlee1025** [comment]
Renamed function and DP1 should be fixed.

**Comment by mgramigna** [comment]
[MG1] I think it makes sense to move `splitInserterAndInsertText` into the declaration of `StructuredFieldPlugin` for a few reasons

* We could export this function as part of the plugin to allow for other files to potentially call it directly down the road to try to re-use as much of the functionality as we can
* Doing this would also allow you to access `opts` and `contextManager` directly, reducing the number of arguments that the function would need to take

**Comment by mgramigna** [comment]
[MG2] Pasting a hashtag inside an inserter pastes a blank space at first instead of the hashtag. When I paste again it works.

This is a super unlikely use case, so after a little investigation if it proves to be a nuisance I would not worry about resolving as part of this PR

**Comment by danlee1025** [comment]
MG1 should be fixed and I will investigate MG2.

**Comment by Dtphelan1** [comment]
Checking in because of the rebase -- has MG2 been addressed?

**Comment by danlee1025** [comment]
Just fixed MG2, it's ready for re-review @Dtphelan1 and @mgramigna.

**Pull request merged**
