### PR TITLE
Shortcut entry overhaul

### PR DESCRIPTION
**Pull request by mgramigna**
You know what it is

### CODE REVIEW

**Comment by mgramigna** [comment]
Test literally everything that has ever had to do with the note editor literally ever. This is a huge overhaul of our note authoring approach, our shortcut model, and just the general workflow of shortcut entry.

Key features:

* Introduce a concept of "incomplete" shortcuts that can be completed via various portals, whether that be expanding a shortcut to show full text or selecting a value for child shortcuts.
    * "Completing" a shortcut happens by either selecting a value, or adding proper context
* Any shortcut trigger should now be insertable into the editor. Triggers with improper parent contexts will remain incomplete until that is resolved.
* No more pick-list for templates and context tray insertion. Will now just create incomplete items.

Godspeed.

**Comment by sgober** [comment]
226 commits. this is wild.

**Comment by mgramigna** [comment]
[MG1] Insert GIST and ONCOHIST. Close and re-open note. Switch condition to Fracture using completion portal. Fracture's ONCOHIST gets inserted 16 times.

**Comment by mgramigna** [comment]
Confident that MG1 doesn't matter at all. It's just hilarious. I believe it is because each line of ONCOHIST is an Inline of type `structured_field`. There are 16 lines in GIST's ONCOHIST. So when the condition switches and it loops through stuff, it adds an ONCOHIST per line. Since this only happens when you close and re-open a note, I think this isn't a priority. Just kinda funny

**Comment by mgramigna** [comment]
[MG2] Really hard to delete dates that were inserted via the completion portal. When I click on one, focus gets stolen and hitting delete does nothing. Only works if I do it really quickly for the split second before focus is stolen. Only happens for the date picker.

Likely a Jira.

**Comment by sgober** [comment]
Re MG2: I thought we had a JIRA for this but I can't seem to find it

**Comment by mgramigna** [comment]
@sgober you're probably thinking of the one where the editor should re-focus after the date picker is closed.

**Comment by mgramigna** [comment]
[MG3] Can't delete placeholders

**Comment by mgramigna** [comment]
MG3 resolved

**Comment by sgober** [comment]
MG1 is worse on `/demo2` because the @ONCOHIST is longer

**Comment by jafeltra** [comment]
[JA1]: Typing a # and trying to click in the portal doesn't input any value. Typing #d and then clicking a value inputs text as expected.

**Comment by sgober** [comment]
[SO1] If #date is the last incomplete shortcut and you use the keyboard to arrow to it and select the date, the sign note button is still disabled until you click somewhere in the editor.

Screen Shot 2019-10-01 at 9 41 32 AM

**Comment by mgramigna** [comment]
Looking at SO1

**Comment by mgramigna** [comment]
SO1 will be solved by ASCODCP-2125

**Comment by sgober** [comment]
[SO2] If a #date is the last word on a line there is no way to enter to the newline because the date completion portal pops up and there is no way to escape out of that and remain in context

this **_should_** also be solved by ASCODCP-2125 but wanted to document

**Comment by mgramigna** [comment]
Made Jiras for MG1 and JA1.

Behavior for SO1 SO2 and MG2 should be covered/tested during ASCODCP-2125. Comments regarding that are on that Jira

**Comment by mgramigna** [comment]
All outstanding comments should be addressed in one way or another.

**Comment by Dtphelan1** [comment]
I feel good with this.

**Comment by mgramigna** [comment]
👀

**Comment by danlee1025** [comment]
Nvm, just had to close and re-open the note... Everything else in the pre-release script looks good!

**Comment by mgramigna** [comment]
this could be it

**Comment by mgramigna** [comment]
MG1 still outstanding

**Comment by jafeltra** [comment]
No worries, Jira already logged [here](https://jira.mitre.org/secure/RapidBoard.jspa?rapidView=553&projectKey=ASCODCP&view=planning&selectedIssue=ASCODCP-2267&issueLimit=100)

**Comment by Dtphelan1** [comment]
Incredible work Scrummaster

**Pull request merged**
