### PR TITLE
New sarcoma patient

### PR DESCRIPTION
**Pull request by laclark22**
New patient and end point "pilot1" for sarcoma patient. Best way to review is to look at the word document associated with the JIRA task and make sure everything is added. I will add a JIRA for the KIT protein as i did not add that. 

https://jira.mitre.org/browse/ASCODCP-1180

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
I rebased the branch with master

**Comment by gregquinn2001** [comment]
[GQ2] Renamed patient to avoid real people. :)

**Comment by gregquinn2001** [comment]
GQ1 and GQ2 are both resolved now

**Comment by nicoleng12** [comment]
[NN1] - In the targeted data panel in the disease status chart, there are two points on the far right that are aligned vertically. They both say March 2, progressing when you hover over the points. It looks like the March 2 progressing data point is too close to the March 27 stable data point and the plot has difficulty distinguishing between the two and as a result only shows the progressing information when you hover, which is misleading to the user. As a fix for this PR, can we just update the date so that they are spaced further apart? We can create a jira for exploring ways to handle cases where the dates are too close.

**Comment by gregquinn2001** [comment]
Nice find on NN1 @nicoleng12 . I saw it but should have explored it more. I'll change the data and create a jira

**Comment by gregquinn2001** [comment]
[GQ3] Uses 30 FEB 2018 as a date but there was no such day!

**Comment by gregquinn2001** [comment]
GQ3 and NN1 fixed.

**Comment by gregquinn2001** [comment]
[GQ4] Key Toxicity should be "upset stomach" mild depends on toxicity.

**Comment by gregquinn2001** [comment]
[GQ5] Diagnosis date happens after some disease status values.

**Comment by gregquinn2001** [comment]
[GQ6] Narrative mode shows no key toxicities (may be due to changes I made)

**Comment by gregquinn2001** [comment]
Resolved GQ4, GQ5, and GQ6

**Comment by gregquinn2001** [comment]
[GQ7] oncotype dx score is for certain breast cancers only (my fault - prob not in word doc)

**Comment by gregquinn2001** [comment]
[GQ8] breast cancer panel should not be checked for GIST cancer summary

**Comment by gregquinn2001** [comment]
Resolved ASCODCP-1234. Support genetic panel for GIST now. code still had breast cancel panel method call. Both KIT and PDGFRA genes added to patient and supported in Flux wrappers (not SHR). Made patient KIT+ and PDGFRA-. 95% of GIST patients are KIT+.

**Comment by gregquinn2001** [comment]
[GQ9] Timeline not showing medications

**Comment by gregquinn2001** [comment]
GQ7 and GQ8 resolved.

**Comment by gregquinn2001** [comment]
GQ9 resolved. Existing issue in timeline and reason why not all medications show up for demo2. no end date and it doesn't show up. Made it set end date to today for meds without an end date for now.

**Comment by nicoleng12** [comment]
This looks good! Tested in IE and in chrome. Backend tests pass and I ran through the demo script.

**Pull request merged**
