### PR TITLE
User profile loaded on SmartCompass

### PR DESCRIPTION
**Pull request by Dtphelan1**
Pretty sure this works now, but I was having a doosy of a time setting it up. Pulls the functionality used in SmartApp (now called SmartFullApp) into a decorator-adjacent function called WithSmartData. That function takes a component as an argument, and returns a new component that extends the previous component and defines a **new** componentDidMount function and render. Render calls the super.render if there are no auth problems, but It does not call the super's componentDidMount right now, and I don't know how well that behavior is supported in react/JS. 

Additional small changes include: 
- Changed Lang to _ in files touched. 
- Added TM character to all Compass display names
- (repeat from above) Changed name of the smart fullapp component from `SmartApp` to `SmartFullApp` since we have two smart applications now.

**Note Well:** The error that caught this whole task up in debugging hell was a lifecycle method that was defined with the arrow notation. As a note, we shouldn't be using the arrow notation when defining lifecycle functions like `componentDidMount`, etc. 

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [x] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [x] Document any new APIs/extension points
- [x] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by mgramigna** [comment]
This looks great. I love the decorator-inspired approach to separating out the functionality from the apps themselves. One slight concern (?), now some of our apps are imported using the Object destructuring notation, while some remain in the standard import ___ from ___ without curly's.

I don't necessarily think this is a big deal, I'm just envisioning down the road this being more of a small nuisance when dealing with these different apps. Not sure if any action really needs to be taken on this, it's just the caffeine talking really.

**Comment by Dtphelan1** [comment]
Great observation with the curly braces, but it has nothing to do with the changes I introduced - this was introduced when we added redux to our app containers. In those container filles (e..g. FullApp) we exporrt the classes by name and the reduxed containers by `default`. It's because of that I import things with Curlies; FWIW in those files the redux connection is a noop, so we could probably remove it with no issue if we don't intend on reduxing more things.

**Comment by Dtphelan1** [comment]
Will rebase after alex shih's note-modal code is merged

**Comment by mgramigna** [comment]
LGTM. Needs a re

**Pull request merged**
