### PR TITLE
Shortcut model refactor

### PR DESCRIPTION
**Pull request by gregquinn2001**
Clean up of shortcut classes plus introduce InMemoryClinicalNote for parsing note text into shortcuts, placeholders, and text. Used by FNE and for Karen's PointOfCare tablet app use of PointOfCare. Basically test the app and everything should still work with no visible new features

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [ ] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by danlee1025** [comment]
[DL1] I get an error when trying to reload a note after editing ONCOHIST section in follow-up template.
Steps to re-create:
1. Create a new note with the follow-up template.
2. Type text into the ONCOHIST section.
3. Close and try to re-open the note.
image

**Comment by danlee1025** [comment]
[DL1] Unable to re-open note when there is styled text in editor.(bold, italics, lists)
image
Might be similar to the bug that you fixed before.

**Comment by gregquinn2001** [comment]
I'll take a look. thanks for double checking Dan.

**Comment by danlee1025** [comment]
[DL2] Cannot insert placeholder from context tray.  Console log is same from DL1.

**Comment by gregquinn2001** [comment]
Thanks @danlee1025 ! DL1 and DL2 should be resolved. All tests still pass.

**Comment by gregquinn2001** [comment]
@jafeltra and @danlee1025  please review when you can so we can get this pr merged!

**Comment by jafeltra** [comment]
This looks pretty good. I can definitely see how much repeated code we had. A few things I noticed:

[JA1] Clicking #date from the context tray freezes the app and eventually gives the following error: Cannot read property 'length' of null at FluxNotesEditor._this.insertShortcut (FluxNotesEditor.jsx:305).
[JA2] There seem to be old commented out console.logs that I think should be removed.

I also noticed some areas that could potentially continue to get refactored. I'll add them here, but we may want to just address them in the INFRA task that is in the sprint to continue the refactor:
- `callMethod` still exists on NLPHashtag but it seems to be very similar (or the same) as the one defined in EntryShortcut. However, I also noticed that NLPHashtag doesn't extend EntryShortcut, which is probably why it still defines its own method.
- Similarly, CreatorIntermediary doesn't extend EntryShortcut, but it has some similar methods, like `getLabel` and `getText`.

**Comment by gregquinn2001** [comment]
For JA1, did you do #enrollment then #date? When I do that it works fine???

**Comment by jafeltra** [comment]
Hm I had done #disease status #reference date #date. I clicked all 3 shortcuts when adding them.

**Comment by gregquinn2001** [comment]
Well, I tried that test case for JA1 too and it works fine too??? Maybe it's mac-related???

**Comment by gregquinn2001** [comment]
JA2 is resolved

**Comment by jafeltra** [comment]
JA2 clean up looks good! It seems really odd that JA1 would be mac-related. I've pulled and restarted yarn and still see it happening. Maybe I'll see if someone else can reproduce it tomorrow.

**Comment by gregquinn2001** [comment]
For JA1, I deleted my local branch and then checked it out from remote fresh. Did a yarn start and now I see it!

**Comment by gregquinn2001** [comment]
Wish I knew the difference as that would help me fix it!

**Comment by gregquinn2001** [comment]
JA1 is fixed! It was actually very simple. Not outstanding issues now I believe so please re-review @jafeltra

**Pull request merged**
