### PR TITLE
[CCP] Fix for overlapping treatment option names

### PR DESCRIPTION
**Pull request by noranda**
This PR satisfies JIRA [2138](https://jira.mitre.org/browse/ASCODCP-2138) fixing a bug where long treatment names would overlap. This PR uses `react-truncate` to handle truncating text after 2 lines using an ellipsis (`...`) and includes hover text to see the untruncated version. To test this, change [this line](https://github.com/FluxNotes/flux/blob/72fef09b1cc1b1a8121a85bf853cb47c8aacf85e/src/mcode-pilot/components/TreatmentOptionsOutcomesTable/TreatmentOptionsOutcomesTable.jsx#L99) to a long string sequence. It should wrap on words or dashes and truncate after the second line.

Example:
Screen Shot 2019-08-02 at 9 32 16 AM

Note: Researched using `react-dotdotdot` over the more popular `react-truncate` as the later uses canvas which requires adding a jest mock library to handle, but did not work in Safari.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by noranda** [comment]
@KeeyanGhoreshi 
[KG1] Fixed!
[KG1] I'm having trouble duplicating this. Can you give a little more detail into the steps you took? Is it landscape or portrait ipad view? When do you refresh?

**Comment by KeeyanGhoreshi** [comment]
For [KG2] I'm on ipad view.  I refresh the page and the bug occurs.  Refreshing the page again doesn't fix it.  I think having the console open might be affecting it but I'm not sure.

**Comment by dehall** [comment]
If the first word is really long (like 25+ characters), it looks like it just truncates there instead of going onto a second line. Is that intended? I'd be worried if the first word is a long medication name then it would hide any combined treatments

image

**Comment by noranda** [comment]
@KeeyanGhoreshi @dehall : I gave this some more thought and decided to go about it a different way. Instead of using truncation to handle longer treatment names, I converted the entire table into an actual html table so that the row heights will change to fit. This allows us to always display all the treatment names without having to worry about overlapping.

**Comment by KeeyanGhoreshi** [comment]
Screen Shot 2019-08-12 at 11 26 57 AM

On the icons view lines that wrap cause the arrow button to move above the name.

**Pull request merged**
