### PR TITLE
Add missing identifier string and MR for missing ccp patients

### PR DESCRIPTION
**Pull request by karenzheung**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

 Address jira 2238. To test go to endpoints /ccp2 and /ccp3 and make sure patient loads. 

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [N/A] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [N/A] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [N/A] Document any new APIs/extension points
- [N/A] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [X] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [X] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Great job Karen! The enpoints definitely seem to work now and I'm seeing the data load through with no issue. And great job fixing some of the data elements! Just a few small things:

[DP1] - Can we fix CCP3's Stage to match that of the excel spreadsheet?
[DP2] - I'm not sure that some of the dates in CCP3 make total sense. I'm gonna check with Zeshan or Jim to validate. If that's the case, I'll ask for changes based on their feedback.

**Comment by Dtphelan1** [comment]
Zeshan's confirmed that some of the date's are a bit funky. In particular: 
1. The 1/7/2015 date might make more sense as 1/7/2016. 
2. The Mastectomy in row 76 should probably have taken place in 2019. That said, we don't even have those last three procedures recorded in CCP3. If it's not too much effort, we should add those.
@karenzheung Do you think you can make these requested changes sometime today? Thanks!

**Comment by karenzheung** [comment]
Rebased. Resolved DP1 and DP2. For the three additional procedures I had them all reference the same clinician but I can change that if it doesn't make sense

**Comment by Dtphelan1** [comment]
re: the clinicians, I'm fine with it for now . If Jim or Rob have feedback then we can change it later. But great work Karen!

**Pull request merged**
