### PR TITLE
Relocate dosage display

### PR DESCRIPTION
**Pull request by sgober**
Handles ASCODCP-1793 (see mockups for what this should look like).  Be sure to test on a variety of sized screens.  In addition, there is still some search/scrolling issues that are captured in ASCODCP-1688 but this does fix the search highlighting for medication names only.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
Backend tests pass and this works in chrome, chrome ipad pro view, and IE.

[NN1] - Can we give more width space to the dosage on the left side of the bar? When resizing the screen, the text seems very narrow. This can also be seen on the pilot1 endpoint. The first medication has a very long dosage and instruction description. The text is very long and narrow, looking a bit awkward. There seems to be some extra padding to the right of the bar that maybe you can use to expand the width of the left side? When resizing the screen, at smaller widths, the  text to the left of the bar will move to the top of the bar. Another option is to trigger that resize handling when the text on the left hand side is very large.

image

**Comment by sgober** [comment]
@nicoleng12 try it now, I went ahead and pushed some styling updates

**Comment by gregquinn2001** [comment]
The range bar shows more clearly in the concepts vs. the app I think. Do you agree? Are we following the sizing specified by Dan in the mockups? axis is 0.5px, #C2C2C2 and range bar is 4px, line gray

**Comment by sgober** [comment]
@gregquinn2001 the visualizer is using all the specs that Dan put in the mockups.  I just made a few minor adjustments to bring the line in front of the range bar like in the mockups but besides that all the colors, widths, etc match

**Comment by gregquinn2001** [comment]
hmm. ok. Do you think they look the same? I feel like it's easier to see the range bar vs. the axis in the mock-ups. Is it just me?

**Comment by gregquinn2001** [comment]
I don't know, maybe it's just my imagination!

**Comment by nicoleng12** [comment]
Thanks Sarah! The styling fixes look good

**Comment by sgober** [comment]
@gregquinn2001 I would agree, although bringing the line to the front does help.  It's probably because the line is shorter in the mockups than the actual code.  Maybe we can ask Dan if there is anything we should tune up?

**Comment by gregquinn2001** [comment]
ok. thanks. Let's leave it. It looks great! Nice job!

**Pull request merged**
