### PR TITLE
New ccp patient

### PR DESCRIPTION
**Pull request by sgober**
Added new /ccp endpoint and moved the /ccp endpoint to /ccp2. This patient is modeled off of Debra and has the data included in the slides attached to the JIRA.  Let me know if you think anything is missing/should be changed.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [x] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] Not sure if this is required for Definition of Done, but the slides on the JIRA show the receptor statuses in the summary section. This would display if we were using the BreastCancer metadata The current metadata being used is the default McodeMetadata; I think ideally we would use the breastcancer metadata for this patient, or a new metadata file we made for this view. 

Either way, I'm shocked that the matchers didn't pair this patient with the BreastCancer metadata. When the CoreCancerPilotSummaryMetadata extends SummaryMetadata, should it also extend it's list of hardCodedMetadata options? Right now I think it just overwrites them. @gregquinn2001 could speak to this better.

**Comment by sgober** [comment]
@Dtphelan1 The receptors are in the patient currently but they are not displayed when using the CCP app.  I played around with Ella and Debra and saw the same thing.  I'm pretty sure that they are not shown by default in the CCP app so that's probably a different addition to make.

**Comment by Dtphelan1** [comment]
@sgober we're on the same page: that's why I mentioned displaying and not capturing, and why I said it might be outside the scope of this task. 

That said, the reason we undertook this new patient was to support viewing the data in the slides; if the current metadata being used by this new endpoint doesn't display the patient data how the slides suggest it should, it might be within the scope of this task to modify the metadata as needed.

**Comment by Dtphelan1** [comment]
[DP2] I know we dont' do this on the current HardCodedPatient, but I think it would be great if we could give this new file a more meaningful name -- like BreastCancerCCPPatient or something in that vein.

**Comment by gregquinn2001** [comment]
@sgober  and I talked about this (DP2). Let's make this a separate JIRA.

**Comment by sgober** [comment]
@gregquinn2001 I can do it here too if that's easier.  If not do you want me to make the ticket?

**Comment by sgober** [comment]
@gregquinn2001 what do you think for DP1?

**Comment by gregquinn2001** [comment]
Yeah @sgober  it would be great if you could create a JIRA task to rename all our patient files based on their content rather than their initial intended use!

**Comment by Dtphelan1** [comment]
@gregquinn2001 I don't think so -- I'm not seeing receptors as a part of the GeneralCancerSummarySection right now, and I think that's where it would be.

**Comment by sgober** [comment]
@gregquinn2001 @Dtphelan1 created a JIRA for DP2 (ASCODCP-1729).  Let me know about DP1.

**Comment by gregquinn2001** [comment]
For DP1, can we generically display a list of receptors statuses. So can we know that ER, PR, and HER2 are receptors without knowing about breast cancer or having a list of the somewhere? That's the question we need to answer

**Comment by sgober** [comment]
@gregquinn2001 I'm not totally sure how to answer that question, any suggestions?

**Comment by gregquinn2001** [comment]
I can take a look at it today when I'm off the call I'm on now. I'll look at the mCODE model and see how they're handled or if we pulled in the old SHRO to handle them and if they can be worked with generically. Is there a way to identify an entry as a receptor is the question I'll be trying to answer.

**Comment by gregquinn2001** [comment]
@sgober  let's create a jira for DP1 for now. More research is required. I don't thing hormone receptor types are a generic cancer concept; I think hormone receptors are specific to breast cancer so I'm not sure if they will be in mCODE. I'll check with May but let's not try to get that into this PR. The data should be in place for the ER, PR, and HER2 values even if they won't display on the ccp endpoint.

**Comment by rdingwell** [comment]
@sgober @gregquinn2001 Receptors fall under a more generic category in mCODE, namely TumorMarker

**Comment by jafeltra** [comment]
[JA1] Tumor size (displayed in the ppt slide) is not displayed in the TDP. I at least see the Tumor dimensions in the JSON, so this may be similar to DP1.
[JA2] The ppt slide shows a "Grade 2" for the tumor. Our "Histological Grade" in the TPD says "high grade or poorly differentiated" which I think would translate to a "Grade 3".
[JA3] The Disease Status value on the chart says Dec 2017. I think for it to make sense to have no other data, and also in line with the ppt slide, this should be Dec 2018.

**Comment by jafeltra** [comment]
[JA4 - more of a question] Are Histological grade and Tumor Histology related? If so, is there a reason why one is missing while the other has data?

**Comment by jafeltra** [comment]
[JA5] I happened to find that there is a note that specifies a #disease status is #stable. I don't think the actual structured data in the JSON reflects that note, given that the disease status chart only has the original diagnosis date. I don't think this is a priority given the fact that there are no notes in the CCP app, but this is probably worth a Jira to make sure the note contents are aligned with the structured data.

**Comment by gregquinn2001** [comment]
For JA2, it looks like histological grade may align with the grade shown in the mockups. For breast cancer, it's grades 1-3 I think as follows:

Nottingham grading system (also called the Elston-Ellis modification of the Scarff-Bloom-Richardson grading system) for breast cancer (1). This system grades breast tumors based on the following features:

Tubule formation: how much of the tumor tissue has normal breast (milk) duct structures
Nuclear grade: an evaluation of the size and shape of the nucleus in the tumor cells
Mitotic rate: how many dividing cells are present, which is a measure of how fast the tumor cells are growing and dividing
Each of the categories gets a score between 1 and 3; a score of “1” means the cells and tumor tissue look the most like normal cells and tissue, and a score of “3” means the cells and tissue look the most abnormal. The scores for the three categories are then added, yielding a total score of 3 to 9. Three grades are possible:

Total score = 3–5: Grade 1 (Low grade or well differentiated)
Total score = 6–7: Grade 2 (Intermediate grade or moderately differentiated)
Total score = 8–9: Grade 3 (High grade or poorly differentiated)

**Comment by gregquinn2001** [comment]
Sorry @sgober . I now think that grade on the mockup does align with the histological grade.

**Comment by gregquinn2001** [comment]
Let's just make it match the mockup as we were told that is clinically correct. We will need to define an encounter 100 for this patient that we will make today with the update script....

**Comment by sgober** [comment]
@jafeltra @gregquinn2001 I updated the diagnosis date and the grade to match the mockups.  Look okay now?

**Comment by jafeltra** [comment]
So I just re-reviewed this and I think this is where all the JA's stand:
[JA1] All set. I added a comment to the Jira 1713.
[JA2] All set. The updated grade looks good to me because it seems like it reflects what Grade 2 is.
[JA3] All set. The updated diagnosis date to 2018 makes sense to me. It matches the biopsy and I think makes more sense given that she is not on any medications and doesn't have any additional disease status values.
[JA4] Outstanding but low priority. I'm not sure if there was ever any answer to this. @gregquinn2001 do you know about this one?
[JA5] Outstanding but low priority. I'm not sure what the right thing to do here is. Do we want to remove notes now or just align the notes and the rest of the structured data on the record as a separate jira? @gregquinn2001 thoughts?

**Comment by gregquinn2001** [comment]
For JA4, they were 2 different elements defined in mCODE v0.1 but neither exists in v0.5 so maybe it was a mistake. Can you create a JIRA to align mCODE generic cancer summary with mCODE v0.5. That should really be a subtask on @daniellee1025  task maybe.

**Comment by gregquinn2001** [comment]
If the notes have no useful additional information we could remove them and any structured data they created and associated encounters.

**Comment by jafeltra** [comment]
The notes don't seem to have any useful data. The only "structured data" in the notes is the one #disease status value, which doesn't have associated structured data, and it doesn't seem like we want any, base on the mockups. The other notes are just plain text and inserters, and the plain text slightly contradicts some of our desired structured data. So I think it is safe to just remove the Clinical Note entries for now.

**Comment by jafeltra** [comment]
While looking through the data related to the notes, I noticed somethings minor:

[JA6] The last staging entry seems to be a duplicate. I think we can remove it.

**Comment by sgober** [comment]
@gregquinn2001 @jafeltra 

Resolved JA6.  ASCODCP-1731 is the JIRA that covers the MCODE changes

**Comment by jafeltra** [comment]
This looks good to me! JA5 and JA6 were resolved. JA4 is included in the same Jira now!

**Comment by Dtphelan1** [comment]
With everything addredssed and rebased I'm all set!

**Pull request merged**
