### PR TITLE
Basic C&P in IE; Update Slate and Slate-Autoreplace

### PR DESCRIPTION
**Pull request by Dtphelan1**
Updates Slate and Slate-Autoreplace, the terminology used in our app to reflect slates new API and changes our copy and paste mechanic so that we can successfully copy and paste basic text in IE. Originally, we were striving to copy and paste structured data, but it appears that the DataTransfer object we use to facilitate shortcut data being copy and pasted is not supported in IE (and no sufficiently similar mechanism seems to exist -- IE just doesn't do robust copy&pasting of things like HTML, files, or application-specific formatted text). 

This PR looked at updating to React 16, but all of the interdependent libraries and cascading changes proved too daunting for this task. 

Things to note: 

1. Enzyme tests using Slate broke with the new update. Discussed this with @gregquinn2001 and @jafeltra. We'll punt on this for now. 

2. Dictation doesn't work in IE or Chrome. This technically was the case with our old code and the newest version of the Dragon Dictation extension for Chrome, but we found a work-around with an older version of the Dragon extension. This work-around is not implemented, because doing so required manually changing the Slate Js library. Discussed this with @gregquinn2001 and we've made JIRA's to address this in future sprints.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- **N/A** Cheat sheet is updated
- **N/A** Demo script is updated 
- **N/A** Documentation on Wiki has been updated 
- **N/A** Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- **N/A** Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- **N/A** Added Enzyme-UI tests for slim mode 
- **N/A** Added Enzyme-UI tests for full mode
- **N/A** Added backend tests for new functionality added
- **N/A** Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
This is in IE?   
  

  
  

  
  
>

**Comment by gregquinn2001** [comment]
Sorry that's an important detail! Yes IE11 on Windows 10

**Comment by gregquinn2001** [comment]
Thanks Dylan!

**Comment by Dtphelan1** [comment]
Polyfill's wont be enough, as a cunk chunk of the code tried to reference the DataTransfer.setData method which is (of course) poorly defined in IE. I've issued a PR for this on Slate and taken the associated code and put it back into our lib folder. I've made a JIRA  to remove this code the moment our PR is merged on Github.

**Comment by Dtphelan1** [comment]
This is not looking great... Going to close this branch for now, as there are a lot of issues still with this branch. Notably: 
1. Shift-left arrow does not select text properly
2. Drag-to-select does not select text properly

**Pull request closed without merging**
