### PR TITLE
Handle promises and introduce a loading animation

### PR DESCRIPTION
**Pull request by Dtphelan1**
Interacts with the new backend and frontend for the treatment options requests, and updates our code to interact with those asynchronous promises. Also introduces a loading animation if the request is taking a long time. 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- **N/A** Cheat sheet is updated
- **N/A** Demo script is updated 
- **N/A** Documentation on Wiki has been updated 
- **N/A** Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- **N/A** Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- **N/A** Added Enzyme-UI tests for slim mode 
- **N/A** Added Enzyme-UI tests for full mode
- **N/A** Added backend tests for new functionality added
- **N/A** Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks good to me! I reviewed the PRs in the other two libraries as well, and those look good as well. I can retest this again once the NPM package is published just to be sure everything is working as expected.

**Comment by mgramigna** [comment]
I agree with Julia. Let's up the version publish to NPM and make sure it behaves the same as linking and then I will approve!

**Comment by Dtphelan1** [comment]
The version on NPM was published yesterday -- people should check to see if this works persistently now!

**Comment by jafeltra** [comment]
Looks good with the new package!

**Comment by Dtphelan1** [comment]
Have I appeased the Gods @mgramigna

**Pull request merged**
