### PR TITLE
Missing criteria table

### PR DESCRIPTION
**Pull request by jessica-oflanagan**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This branch adds the feature to click on a clinical trial and select the "Missing Criteria" action - a subsection below will display the patient's criteria and additional criteria that the trial requires.  

The only trial on display currently is Patina, as the FHIR patient used to find trial eligibility is only eligible for patina.  Switching to another patient_id in ClinicalTrialsList would allow other trials (currently PALLAS is the only other) to be on display.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added Enzyme-UI tests for slim mode 
- Added Enzyme-UI tests for full mode
- [x] Added backend tests for new functionality added
- Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jessica-oflanagan** [comment]
[JA1] I forgot to add the "additional criteria" length to the number of total criteria.  This should be fixed now!
[JA2] Julia and I discussed this, but Gregg said the goal was just to be able to view the table before clicking on the action.  Showing it only after clicking an action might involve a bit more work, but I think that could be maybe be a future task.
[JA3] I removed setFullAppState from the props, and made a few more helper functions so it isn't passed throughout all the files.  One thing I did notice is that "setFullAppStateWithCallback" still exists in some props - I didn't change that yet but again it might be a good idea for a future task?

Also, I think that the buttons are slow because the actions are being processed from SummaryMetadata instead of FullApp, but I'm not entirely sure.  Could have to do with running CQLExecutionEngine as well.

**Comment by lucyxubroad** [comment]
Great! [LX1], [LX2], [LX3] look good!

**Comment by jafeltra** [comment]
This looks good! JA1 and JA3 are addressed. I think we can probably talk to @gregquinn2001 later and decide if JA2 should be a jira task. We can also look further into the speed issue later, maybe making that a jira task if we think it's necessary.

The only other thought I had was I keep clicking on the "5 of 6" in the Criteria fit column to view missing criteria. This is more of a design thought, but maybe it makes sense to have the action on that column. I think that can be a separate Jira as well though.

**Comment by jafeltra** [comment]
This is my last question. [JA4] Should we be able to view the missing criteria if a note is open? It seems like it makes sense to have it either way. If so, I think it's a really small fix.

**Pull request merged**
