### PR TITLE
Scroll to open note search results; highlight closed clinical note search results on hover

### PR DESCRIPTION
**Pull request by mgramigna**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Originally for Jira 1257: Scroll to matching search result of note when clicking on a search result that is a note. The way the task ended up deviates from this a little bit:

Important Changes:
* Clicking/hovering over a search result that is a (non-open) clinical note will no longer open that note. It will highlight that note icon in the note assistant.
* We now index the content of an open clinical note separately, so search results for an open clinical note behave differently (this is where the scrolling comes in)
    * Clicking/hovering over a search result that is part of an open clinical note will scroll the block of text containing that search result into view in the editor.
    * These search results that are part of the open clinical note are prioritized over others and will appear first out of the clinical note search results
* Integrated Elasticlunr.js with for an actual indexed approach of data
    * Search results now have a score associated with them for how closely they match and they are sorted by score
    * Try making some typos!
* Inegrated fuse.js for exact matches of the content of an open clinical note. This allowed us to be able to retrieve the index of the match for scrolling.

Jiras resolved as a part of this task:
* 1435: Removed conditional logic from PatientSearch.jsx for interacting with search results, so different results can specify a different onClick or onHighlight when the data is actually indexed
* 1382: Use a 3rd party client side indexer. Allowed for much better searching of note data and improved the indexing of note content (able to retrieve index of match, etc.)

Resulting Jiras:
* 1446: When searching, highlight matched text and data in an open clinical note
* 1447: If the screen is especially small, meaning a block of text takes up more than what's in the visible editor, we need to scroll to the specific matching text rather than the block
    * Might be solved by related work for 1446

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] I think you were right. We should put some visual indicator of results in the open note - maybe just a prefix
[GQ2] Can we not include the open note in the indexing of the note list on the right? In other words, we shouldn't get 2 results for the same hit if the note happens to be open.
[GQ3] It looks like a note stays highlighted on the right even if the current highlighted result is in the open note?

**Comment by gregquinn2001** [comment]
This is so awesome though! I think users will love the search capability and it's a great demonstration of the power of structured data!

**Comment by karenzheung** [comment]
Should the note stay highlighted after scrolling to a different result?

**Comment by mgramigna** [comment]
Addressed GQ1 and GQ2. Working on GQ3 and Karen's comment now; they're closely related

**Comment by mgramigna** [comment]
Resolved all comments and rebased

**Comment by mgramigna** [comment]
rebased

**Comment by mgramigna** [comment]
[MG1] As a result of solving GQ3, highlighting doesn't persist after note result is selected

**Comment by mgramigna** [comment]
Fixed MG1

**Pull request merged**
