### PR TITLE
Most-recent-visit looks only at previous visits

### PR DESCRIPTION
**Pull request by Dtphelan1**
Fixed the functions called by most recent visit summary to only look at previous encounters, and not just any encounter on the record. To test, run the patient-date-updater with Ihanos with the following: 
```
yarn patient-date-update src/dataaccess/GistAdjuvantIhanos.json 100
```
And then look on /pilot1 to confirm. 

**QUESTION**: In the process of fixing this, I noticed that the patient date updater doesn't seem to update ConsultNotes properly. Specifically look at ConsultRequested entry with ID 5900 before and after running the updater; the updater pushed the encounter.timePeriodStart to April 11, visible in the Most Recent Visit section, but the CreationTime value, the LastUpdated value, and importantly the date on the associated note all say April 10. This disparity will likely cause confusion and should be addressed, but I didn't think it fell under the scope of this task. What are people's thoughts on this? Is it sufficient to make a jira for now?

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
On the question Dylan, could that issue with the patient date updater explain why the most recent date appeared to be working before or stopped working? It does sound like a new JIRA!

**Comment by gregquinn2001** [comment]
[GQ1] 
image

If the Date of Last Visit with You is set to 21 Feb 2019 but the date of last visit here is null. I think it should be 21 Feb 2019 and who should be Dr. Mona Brown.

**Comment by Dtphelan1** [comment]
The problem is either that the consultRequested I’m looking at doesn’t have a location value and/or the Default User objects don’t have a location. Should I change those? If so, does Hospital X suffice?
  

  
  

 Also - Do we want to change the default hospital to be Hospital X when you make a new note? Right now it’s Dana Farber and that seems to imply the Mona works at both.   
  

  
  

  
  
>

**Comment by gregquinn2001** [comment]
This use to work! I don’t understand when it broke and why still!

Yes, Mona should work at one hospital although it's not unrealistic to work at two.

**Pull request merged**
