### PR TITLE
remove refills from med viz

### PR DESCRIPTION
**Pull request by sgober**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:
JIRA 1833.  Be sure to test resizing to make sure it all looks good with removing the column

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Not introduced here, but [DP1] our font-sizes don't seem to actually match the designs specified  in 15.4. Is there a JIRA for this that we know of? If not I'll make one.

**Comment by Dtphelan1** [comment]
[DP2] While we're fixing the column sizes though, can we make the bottom row containing Route, Prescribed, and Prescribed By use the full 12 units of space instead of just 11?

**Comment by sgober** [comment]
@Dtphelan1 
[DP1] Are you just referring to the titles of the medications? That's the only one that I see that's wrong. I just took care of it.
[DP2] Done.  Not sure why it was only 11, it was like that when I started the med viz stuff.

**Comment by Dtphelan1** [comment]
For DP1, at least on my end, it looks like the med-info headings are defined in `rem` units instead of being set as 12px as hinted at in 15.3 design docs. Of course, it's hard to say for sure what the styling there should be since those mockups don't actually include a full med-info section in the way our current implementation shows it.

**Comment by sgober** [comment]
For DP1: I'm not sure the mockups cover any changes to the medication info part of the visualization.  It would certainly be an easy fix to make it 12px though.

**Comment by Dtphelan1** [comment]
The only thing I'm working off of on that is the fact that route is included in the mockups and in our current implementation we have route in the med-info section. I leave it up to you -- again it is outside the purview of your immediate PR. For comparison:

As-is: 
image


With 12px:
image

**Comment by sgober** [comment]
Just took care of it.  I made both the heading and the field 12px because they appear to be the same size in the mockup.  We can easily change that later though.

**Comment by nicoleng12** [comment]
This looks good Sarah. DP1 and DP2 have been addressed, tests pass, and this looks good in chrome, ipad pro view, and IE

**Comment by Dtphelan1** [comment]
This looks good to me!

**Pull request merged**
