### PR TITLE
Timeline updates

### PR DESCRIPTION
**Pull request by jafeltra**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This pull request addresses Jira 1364 (and Jira 770). It makes various improvements to working with the timeline. I upgraded our version of the react-calendar-timeline to fix some of the issues we had. These improvements include:
- Added zoom buttons that zoom in to a specific time range (ex. 1 week, 1 year, 3 years)
- Added a "Today" button to scroll the timeline to put today in view
- Added panning buttons that scroll the user forward and backwards on the timeline
- Removed the ability to zoom the timeline by clicking on the timeline headers
- Support the timeline on a touch screen by added tooltip support for when tapping on an item
    - To open a tooltip on touch, a user must be actively pressing on the item. We can investigate further options as a separate task.
- Fixed the bug that caused the timeline lose the ability to drag to pan if it was initially rendered off screen. (Jira 770).
- Fixed how we update the timeline when changing wide to not wide view (when a note is opened and closed) so it resizes to be the correct length of time shown.

This task also included investigating adding a minimap to the timeline to see where you are in comparison to the full timeline. However, this will not be a simple task. Instead, hopefully some of the other improvements to the timeline make it easier to work with and will ease the need for a minimap.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [x] Documentation on Wiki has been updated 
- [x] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
I think you may have fixed JIRA 629!
[GQ1] Any chance we could go back to scrolling if we keep dragging and re-enter timeline area? Right now if we leave and then come back, we have ended the drag.

**Comment by danlee1025** [comment]
Looks very good!  Nice work!  After GQ1 is addressed I will approve this PR.  This does need a rebase though.

**Comment by jafeltra** [comment]
I don't think GQ1 will be easy to fix since the react-calendar-timeline is handling canceling the drag when your mouse leaves the timeline. Maybe we can make this a separate Jira?

**Comment by jafeltra** [comment]
I don't think I did fix Jira 629 sadly. I can still get the hover to flicker.

**Comment by jafeltra** [comment]
Rebased!

**Pull request merged**
