### PR TITLE
Filter timeline by over the counter meds

### PR DESCRIPTION
**Pull request by jafeltra**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Jira 1491

This adds support for adding filters on subsections. The section will know how to handle changing the data based on the filter value. The available options of filters are displayed at the section level in the targeted data panel. If the section has no filters available, the filter button is not displayed for the section.

The only filter that is added right now is an Over The Counter Medications filter on the timeline. It is defaulted to on. Unchecking the filter removes the over the counter medications from the timeline. In order to determine if a medication is over the counter, I updated the hardcoded patient JSONs to use an actual medication object, rather than a codeable concept. Medications have a flag for overTheCounter.

This PR also fixes two bugs. It changes the color of the text for the condition name at the section level back to grey. It also updated the getNameSuffix function to set state only when the nameFunction returns, which fixed a bug where the timeline was not rendering the correct dates when initially loaded.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Let's create a JIRA to store the filter value setting in the user preferences. Otherwise, looks great!

**Comment by gregquinn2001** [comment]
What's the conversation with Matt about before we can merge? Rebaseline issue?

**Comment by jafeltra** [comment]
No the branch should be up to date. I realized there is a `removeDataBySection` function that has to do with indexing the data for search that I hadn't called, but search seems to be working, so I was wondering what the function was for and if I should have called it.

**Comment by jafeltra** [comment]
Talked to Greg and I think this is all working correctly, so I'm going to merge now!

**Comment by mgramigna** [comment]
wut

**Pull request merged**
