### PR TITLE
Pathology report

### PR DESCRIPTION
**Pull request by karenzheung**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

JIRA 1505
Test on pilot1

Pathology section now shows date of pathology report and can open the report.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] Can you just rename the action to "View Source Attachment" instead of just "View Attachment"

**Comment by gregquinn2001** [comment]
[GQ2] We need to put a different name on the pathology report (the pathologist). It shouldn't be our medical oncologist.

**Comment by gregquinn2001** [comment]
[GQ3] Change "Date" name to be "Report Date"

**Comment by gregquinn2001** [comment]
[GQ4] The date of the pathology report should be shortly after the biopsy or surgery

**Comment by gregquinn2001** [comment]
I am addressing all of these and will make a commit to your branch for them. hope you don't mind

**Comment by gregquinn2001** [comment]
Addressed GQ1-GQ4

**Comment by mgramigna** [comment]
[MG1] Remove unnecessary constructor to get rid of the warning in the console.

https://github.com/FluxNotes/flux/blob/c222f1fef57e90ac2f7573fef273c686ea39b737/src/model/finding/FluxPathologyReport.js#L6-L8

**Comment by mgramigna** [comment]
Resolved MG1 and DL1

**Pull request merged**
