### PR TITLE
[CCP] Implemented Similar Patients section of Treatment Options Selector

### PR DESCRIPTION
**Pull request by noranda**
This PR implements the similar patients section of the CPP treatment options selector using hardcoded data (except for demographics). It is based on v.5 of the designs (on [JIRA task](https://jira.mitre.org/browse/ASCODCP-1568)). Created new components `SimilarPatientsSelector` and `OptionsCheckboxList` to handle selecting options using Material-UI's `Checkbox` component.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter: Noranda Brown

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
This looks really good! I just had some comments

[NN1] - In the mockups (v0.5 of the designs), the blue used for the similar patients section looks a little bit lighter than what is used here. The style guide [https://github.com/standardhealth/shr_design/blob/master/design/fluxnotes_deliverables/shr_fluxnotes_styleGuide_v4.pdf](url) specifies #028DEA for interface elements. Should that color be used for "select all" and "select none"?

[NN2] - In the v0.5 designs, the number ranges are in blue (in age, age at diagnosis, size and ECOG score). I'm not sure how important it is to color those but it seems like it's a nice way to highlight the range

[NN3] - In the v0.5 designs, the check boxes are clear with a grey checks whereas this PR has blue check boxes with a white check. I don't have strong preference either way but wasn't sure how closely you wanted to follow the mockups

[NN4] - This is more of a comment then something to address. I noticed in the designs that there are people icons next to the filter items. Should those be added as well? What do they represent? Some of the items in the mockups have 1 person icon whereas others have 2 or 3 people in the icon

All backend tests pass and this looks good in both IE and chrome

**Comment by noranda** [comment]
[NN1] - I didn't see the style guide! I think this is more Interface Blue Text specific since it is interactive text, so I changed the color to be `#0079CA`.

[NN2] - These colors indicate that you can interact with the ranges to change them, but we haven't implemented that yet. Once we do, the color will change.

[NN3] - I had kept the colors the same as what was implemented on the other Treatment Options view. I can change the colors, however the newest designs remove the checkboxes, so probably not worth the effort.

[NN4] - The person icons indicate how many people (relatively) each option includes, but I didn't include this as we don't have this hooked up yet. This is also removed in the most recent designs.

**Comment by nicoleng12** [comment]
NN1 looks good! NN2, NN3, and NN4 can wait. I read your comments and that makes sense. Thanks!

**Comment by noranda** [comment]
Rebased.

**Pull request merged**
