### PR TITLE
SMART on FHIR OAuth Implementation

### PR DESCRIPTION
**Pull request by lucyxubroad**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Addresses JIRA 64: Implementation of SMART on FHIR OAuth.
- Allows for user authentication through the EHR.
- New /smart endpoint will read the user and show name on top left under Flux Notes
- New /smart endpoint will also read the selected patient and display either Deborah Hernandez or Ella Ortiz

New Files Made:
- _src/components/LaunchPage.jsx_: page to launch authorization of EHR user, redirects to the /smart endpoint. 
- _src/containers/SmartApp.jsx_: container for the /smart endpoint page, handles reading of patient and user once user authorization has passed, reads the selected patient and loads either Deborah or Ella accordingly

To Test SMART on FHIR OAuth:
- yarn start
- Go to the [SMART App Launcher Sandbox](https://launch.smarthealthit.org/?auth_error=&fhir_version_1=r2&fhir_version_2=r2&iss=&launch_ehr=1&launch_url=&patient=&prov_skip_auth=1&provider=COREPRACTITIONER4%2CSMART-1234%2CCOREPRACTITIONER1&pt_skip_auth=1&public_key=&sb=&sde=&sim_ehr=1&token_lifetime=15&user_pt=)
- In App Launch URL, enter http://localhost:3000/launch
- Click Launch App
- Sign in as the user
- Choose a patient (choosing Pok Abbott should display Ella Ortiz and choosing Buena Abbott should display Deborah Hernandez)

Notes: 
- There is currently a dependency warning, which is caused by our version of React. Once we upgrade React, that should no longer be an issue. 
- If user authentication fails, the /smart endpoint will show just an empty loading screen.
- Going straight to /launch (and not through the sandbox) will cause errors because Flux Notes can't authorize user. 

## Submitter: Lucy Xu

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- Demo script is updated 
- Documentation on Wiki has been updated 
- [x] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added Enzyme-UI tests for slim mode 
- Added Enzyme-UI tests for full mode
- Added backend tests for new functionality added
- Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

-- 
Lucy Xu 
Cornell '21

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] Should the client id be in the code or configurable or protected?
[GQ2] Can we generate the launch URL relative to initial URL of the EHR? If we deploy this to fluxnotes.org for example, it wouldn't work, right?

**Comment by gregquinn2001** [comment]
[GQ3] If I go directly to /smart, the app just hangs forever on loading... Can we set a timeout and return 403 forbidden or a not authorized http error code??

**Comment by nicoleng12** [comment]
This is pretty cool! Nice!

[NN1] - Can you add the descriptions in the description of this PR that you have for each of the new files you created to the files themselves? I think those descriptions are good summaries for what the purpose of the file is and after this PR is closed we will lose those descriptions.  
image

**Comment by lucyxubroad** [comment]
@gregquinn2001 Latest push addresses [GQ3]. I added an "Authorization Fail" screen if authorization fails or if user selects a patient not in our user map.

@nicoleng12 Latest push also addresses [NN1]. I just added comments to the my two added files (SmartApp and LaunchPage).

**Comment by nicoleng12** [comment]
Looks good!

**Pull request merged**
