### PR TITLE
Correctly resize line charts

### PR DESCRIPTION
**Pull request by nicoleng12**
This PR addresses issue 877.

Added responsive container around line chart to handle resizing correctly. Implemented same fix that was used to fix the resizing issue for the progression line chart.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added Enzyme-UI tests for slim mode 
- N/A Added Enzyme-UI tests for full mode
- N/A Added backend tests for new functionality added
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
I just rebased this branch.

**Comment by jafeltra** [comment]
[JA1] The dots on the graphs aren't showing up for some reason when the lab graphs initially load.

**Comment by gregquinn2001** [comment]
Oh yeah. I Didn't even notice JA1! That's weird. I tried it on IE and other than JA1, it seems good. I tried to reproduce JA1 on fluxnotes.org and it doesn't happen.

**Comment by nicoleng12** [comment]
Nice find @jafeltra ! Also thanks for rebasing. I fixed JA1

**Comment by jafeltra** [comment]
JA1 is resolved! Looks good!

**Pull request merged**
