### PR TITLE
Fixing issue where tumor markers where not filtering patient records

### PR DESCRIPTION
**Pull request by rdingwell**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:
This PR fixes an issue that was introduced when deriving initial filtering criteria from a patients record.  Tumor markers such as ER,PR and HER2 where added to the filter under a different property name and resulted in the filtering functionality from not being able to make use of them. 

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [ ] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] - One thing that could help future-us is a comment that links these magic strings back to some other part of the code. Where is "EstrogenReceptor" as a keyword defined in our code? Is it a key used by the TreatmentOptionsService? Some comment explaining would be helpful. 

Looks good to me on the whole though! I'll approve after DP1 is addressed.

**Comment by gregquinn2001** [comment]
Dylan great comment but this code looks breast cancer specific. I also still see treatment option and side effect lists hard coded. Why aren't we letting the API define these even if the cancer linq implementation of that api won't provide them? The provider on the compass side can have methods that return these hard-coded lists for the cancerlinq case for now. I'd still like to see our UI code be cancer agnostic and driven by data provided by the service(s) (yes we should consider supporting multiple!).

**Comment by rdingwell** [comment]
Completely agree with both comments and it's on the list of things to think about.   I'ld like to get this functionality moving toward defining these as mCODE based elements so tumorMarkers would be categorized as being a tumor marker and the codes that are in the elements define the meaning.  Same for staging, treatments ....

**Comment by gregquinn2001** [comment]
Sounds good Rob. Should we get tasks in the backlog in there to work toward this or are you thinking this can't happen for a while?

**Comment by Dtphelan1** [comment]
Okay so long as some tasks are made in the backlog to track this I'm fine approving.

**Comment by mgramigna** [comment]
This has two approvals, so i am going to rebase and merge

**Pull request merged**
