### PR TITLE
View missing criteria placement

### PR DESCRIPTION
**Pull request by jessica-oflanagan**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Previously, the 'Missing Criteria' action was only available when clicking of the name of the clinical trial.  Now, a user can view 'Missing Criteria' by clicking on the 'criteria-fit' field as well.  

Future work: Currently 'Missing-Criteria'  can only be displayed by clicking the action under 'Name' and 'Criteria Fit', but it could be easily displayed on the rest of the row by adding the appropriate column numbers to the displayForColumns array where the action is defined (in the ClinicalTrials section of SummaryMetadata).

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- Demo script is updated 
- Documentation on Wiki has been updated 
- Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added Enzyme-UI tests for slim mode 
- Added Enzyme-UI tests for full mode
- Added backend tests for new functionality added
- Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks good! I can view missing criteria from both columns now! This needs to be rebased and it looks like it will have merge conflicts. Once those are set, I will approve it!

**Comment by nicoleng12** [comment]
Looks good!

**Comment by jessica-oflanagan** [comment]
Just rebased!

**Comment by jafeltra** [comment]
NN1 looks like it is fixed!

Sadly I did find something else. I'm not sure if I missed it before or if it happened during the rebase:
[JA1]: The Enroll Patient action is missing in the list when a new note is open.

**Comment by jafeltra** [comment]
This looks good now! Once Travis passes, I'll approve and merge.

**Pull request merged**
