### PR TITLE
Fix selection on copy that caused paste errors for structured fields

### PR DESCRIPTION
**Pull request by mgramigna**
Jira 1810. If the zero-width space at the beginning of a structured field was not selected when copying, pasting threw an error.

Replicating the error on master:

* See the [zero-width space section](https://github.com/FluxNotes/flux/wiki/Slate-Debugging-Tips#zero-width-spaces) of the Wiki page for Slate debugging and modify the line in `leaf.js` to get the node keys to show up in the editor. It's hard to consistently replicate the behavior without doing this so it might make testing easier.
* Open a new note and insert GIST condition
* Copy all the text up to the start of the "G" but do not include the "0" key in the selection: 
image
* Try to paste the text on a different line, should get this error: 
image
* NOTE: If the selection includes the "0", the pasting will not throw an error on master.

-----

On this branch, that exact behavior should no longer throw an error. I added code in `StructuredFieldPlugin` to detect the error case and extend the selection to include the zero-width space before the `Inline` if applicable.

NOTE: This bug currently only applies to Inserter shortcuts since they are non-void. Once Karen's PR get's merged, all shortcuts will be non-void I believe.

Shortcoming: This doesn't fix copy-paste of structured fields on Safari, but that is broken on master as well.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This fix looks really nice! I found one thing that is potentially a JA1, as long as it is intended to be covered in this Jira.

[JA1] Highlighting the structured field left to right without grabbing the zero width space on the left still causes the error. I'm guessing we just need another check in the if statement for fixing the fragment it uses.

**Comment by mgramigna** [comment]
JA1 resolved

**Comment by jafeltra** [comment]
JA1 looks good now!

**Comment by Dtphelan1** [comment]
Needs a rebase. Reviewing now

**Comment by Dtphelan1** [comment]
Found on master, so we can make a jira but FYSA: [DP1] Copy doesn't work when I select to the very end of the line by using the arrow-down key. 

To replicate: 
1. Create a new note
2. Insert "anything". 
3. Copy this to your clipboard. Confirm it was copied properly by pasting.
4. Remove all content from your editor 
5. Hit the enter key twice just to give some padding 
6. Insert GIST
7. HIt enter twice again for padding 
8. Move selection cursor to the front of the Gastro line
9. Holding shift, press the arrow -key down. This should expand your selection so that it covers the whole line. 
10. Try to copy.

The bug: Your clipboard doesn't change at all. This can be confirmed by pasting. "anything" should be pasted. 

NOTE: 
- Interestingly, if while holding the shift button down you arrow-left after your arrow-down, the copy will work. We can see that what happens is that the zero-width space is exlcuded from the cursor.
- This isn't limited to Structured Phrases, this is just the first place I noticed it. You can trigger the same issue if you use shift + down-arrow to select plaintext. 
- Like I said, this occurs on master.

**Comment by mgramigna** [comment]
@Dtphelan1 Seems like a Jira to me. Doesn't actually touch the code that I wrote either... strange :/. I think arrow key selection as a whole has tended to be a little off in the past.

**Comment by Dtphelan1** [comment]
Since it's agreed that's a JIRA, I'm all set -- couldn't find any other bugs while messing around for 15 minutes.

**Comment by jafeltra** [comment]
This looks good to me now! We made one other Jira for an error we noticed, but it doesn't reach any new code in this PR, it's just within Slate. Also, the error happens on copying, but pasting still works correctly, so I don't think it's any hug issue.

Besides that, I tried copy and pasting from various directions with combinations of grabbing and not grabbing the zero-width spaces, and it all looks good to me!

**Pull request merged**
