### PR TITLE
Mrn number in header

### PR DESCRIPTION
**Pull request by sgober**
Added MRN number into summary header (next to patient name)
Test this using the iPad Pro dimensions in developer tools and make sure it works for all patients.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] When I look at these in the iPad and iPad Pro viewers in Chrome, the columns overflow. Unclear to me if we need to worry about these general iPad modes or if we only need to target the actual iPads we have. For reference: 

Pro
ipadpro

Regular
ipadreg

**Comment by gregquinn2001** [comment]
For DP1, IPad Pro in landscape mode is our target usage with least pixels.

**Comment by Dtphelan1** [comment]
Then DP1 Revoked 👍

**Comment by Dtphelan1** [comment]
otherwise I think this looks good 👍

**Pull request merged**
