### PR TITLE
Generic criteria

### PR DESCRIPTION
**Pull request by karenzheung**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

JIRA 1325
Can now search on more optional criteria. 

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by karenzheung** [comment]
Resolved GQ1

**Comment by karenzheung** [comment]
Rebased

**Comment by Dtphelan1** [comment]
Looks good to me!

**Comment by Dtphelan1** [comment]
Ehhhhh... One comment: Looks like now the options we use fails to return any data because of how selective it is. Do we want to change this, or is this okay? @gregquinn2001 looking at you for feedback.

**Comment by gregquinn2001** [comment]
Yeah I think we can relax the criteria again to get the 3 points at least on pilot1. I thought it was down to 1 or 2 which would be ok too for now I think. If it's no data, that's not good because you can't see the viz at all!

**Comment by Dtphelan1** [comment]
Okay so I'm going to make two changes: 
1. Update the treatment options package version post-publish.
2. Remove one of the criteria s.t. we have all our data points displayed.

**Comment by Dtphelan1** [comment]
Leaving in the commented out dxGrade and gender for future use when we have better data on the backend. If people feel strongly I can remove the commented out code.

**Comment by Dtphelan1** [comment]
I'm satisfied, but would love someont to double checkt his before merging. All the other libraries and packages have been updated

**Comment by Dtphelan1** [comment]
Rebased again, going to merge now with @nicoleng12 's verbal approval!

**Pull request merged**
