### PR TITLE
Shortcut model refactor

### PR DESCRIPTION
**Pull request by danlee1025**
Addresses JIRA-2043.

- Documented the definition of `getKey`, `getText`, `getDisplayText`, and `serialize` functions in `Context` and `Shortcut` base classes.
- Removed `getLabel` and replaced with `getDisplayText` to eliminate ambiguity with labels like `#status`.
- Removed `getText` from `EntryShortcut` and `CreatorIntermediary`.
- Removed `SingleHashtagKeyword` and replaced all instances with `CreatorBase`.

There are no new features as this PR just clarified definitions of functions and refactored some functions/classes in our shortcut model.  Test shortcuts/placeholders specifically and make sure everything is displayed correctly in note editor and context tray.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
-  Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
-  Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
-  Document any new APIs/extension points
-  Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks good as a continuation of the refactor! I tested out all the shortcuts and only found one issue:

[JA1]: Using #reduce medication #to gives the following error:
`Uncaught TypeError: Cannot read property 'length' of undefined at ShortcutManager.js:344`

**Comment by mgramigna** [comment]
FWIW: JA1 happens on the base branch. Looks like `this.triggersPerShortcut` in `ShortcutManager` is behaving strangely for #to 

This makes me think that for subsequent PRs on `shortcut-entry-overhaul`, we might want to consider developing a list of shortcuts that we should test to make sure nothing breaks, specifically noting ones that have caused problems on the branch in the past? I think JA1 was introduced by #691. Sorry :)

**Comment by mgramigna** [comment]
[MG1] We should just be able to remove the `SingleHashtagKeyword` file, right?

**Comment by danlee1025** [comment]
Yea... I must've somehow brought in back in the rebase... removed now.

**Comment by jafeltra** [comment]
I had been checking bugs on the base branch but I guess I must have missed JA1. If it already happens on the base branch, I don't think we need to fix it here.

**Comment by danlee1025** [comment]
Created a separate JIRA to capture the other comments.

**Pull request merged**
