### PR TITLE
Support keyword and hashtag-based child shortcuts

### PR DESCRIPTION
**Pull request by danlee1025**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This PR addresses JIRA-1374.

Implemented functionality to support keywords for `CreatorChild` shortcuts with or without `#` prefix.  
For example, if you are trying to capture data for `#disease status`, you can then enter either `#stable` or `stable` and both will be captured as structured data.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
-  Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
-  Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added Enzyme-UI tests for slim mode 
-  Added Enzyme-UI tests for full mode
-  Added backend tests for new functionality added
- [ Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
This is very cool! Now I want NLP as well! :)
[GQ1] When I do #toxicity and then @act and choose @active medication I get the list of medications but when I choose one it goes back to autocomplete for @act again and I have this stack trace:
Uncaught TypeError: Cannot read property 'createEntryReferenceTo' of undefined
    at FluxToxicReaction.set (FluxAdverseEvent.js:89)
    at baseAssignValue (lodash.js:2580)
    at assignValue (lodash.js:2496)
    at baseSet (lodash.js:4000)
    at Function.set (lodash.js:13652)
    at SingleHashtagKeyword.setAttributeValue (SingleHashtagKeyword.jsx:164)
    at InsertValue.setValueObject (InsertValue.jsx:212)
    at Object.onPortalSelection [as onSelected] (FluxNotesEditor.jsx:419)
    at ContextPortal.onKeyDown (ContextPortal.jsx:115)
    at HTMLDocument.ContextPortal._this.handleKeydownCP (ContextPortal.jsx:98)
set @ FluxAdverseEvent.js:89
baseAssignValue @ lodash.js:2580
assignValue @ lodash.js:2496
baseSet @ lodash.js:4000
set @ lodash.js:13652
setAttributeValue @ SingleHashtagKeyword.jsx:164
setValueObject @ InsertValue.jsx:212
onPortalSelection @ FluxNotesEditor.jsx:419
onKeyDown @ ContextPortal.jsx:115
ContextPortal._this.handleKeydownCP @ ContextPortal.jsx:98

**Comment by danlee1025** [comment]
GQ1 should be resolved and I rebased!

**Comment by nicoleng12** [comment]
This looks great! Really cool. Just one question. I noticed that this doesn't work for enrollment. So if I type #enrollment, i still have to put a hashtag before the trial. Is that expected behavior?

**Comment by nicoleng12** [comment]
Thanks for adding enrollment. Looks good

**Pull request merged**
