### PR TITLE
support updating key toxicities. support showing source clinical note…

### PR DESCRIPTION
**Pull request by gregquinn2001**
support updating key toxicities. support showing source clinical note for updated toxicities.

toxicities were not being created correctly on patient. we had nothing displaying them before so we never realized it.

resolves JIRA ASCODCP-1179

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X ] Manually tested in Chrome
- [X ] Manually tested in IE

**Documentation**

- [X ] This pull request describes why these changes were made
- [X ] Recognizes any potential shortcomings/bugs in the description 

**Code Quality**

- [X ] 4-space indents - convert any tabs to spaces
- [X ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X ] Code is commented

**Tests**

- [X ] Existing tests passed

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This is cool! I have one question. Is there any way to set the Blood Clot toxicity? Also, one bug I found:

JA1: When deleting #toxicity, I got the following error, whether or not an adverse event and grade are added:
Uncaught TypeError: Cannot read property 'constructor' of undefined
    at FluxCondition.js:155

**Comment by gregquinn2001** [comment]
for clotting: use #Superficial thrombophlebitis, #Portal vein thrombosis, #Disseminated intravascular coagulation. There may be some others that should be supported...

**Comment by gregquinn2001** [comment]
JA1 should be resolved

**Comment by nicoleng12** [comment]
This looks good! Functionality looks good and JA1 has been addressed. Backend tests pass and I ran through the demo script and it works as well

**Comment by jafeltra** [comment]
JA1 looks fixed! This needs to be rebased and it looks like there will be conflicts in the rebase.

**Pull request merged**
