### PR TITLE
Shortcut invalid date

### PR DESCRIPTION
**Pull request by sgober**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

Covers JIRA 2027 and also fixes JIRA 2028.  Dates should now be defined and also shown if there is a default date set.

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
I can't seem to get the bug in Jira 2028 to happen on shortcut-entry-overhaul so I can't confirm that it was fixed as part of this, but I guess at least it's fixed! I'm not sure if I'm doing something wrong to replicate it.

One bug I noticed:
[JA1] When typing #disease status #stable #as of # date, the date in the TDP defaults to a date in the future,  not today.

Since I am taking over this PR while Sarah is on vacation, I'll look into my JA1.

**Comment by sgober** [comment]
Thanks @jafeltra!! Miss y'all

**Comment by jafeltra** [comment]
I think JA1 should be fixed. It stemmed from how we have dates in a bunch of different formats so when we parsed the dates, they were expecting to coming in the wrong format. I think we should fix that eventually (I know there's a Jira), but figured it was out of scope on this PR, so I tried to support both formats coming in.

**Comment by Dtphelan1** [comment]
Noticed that since we've fixed the invalid dates by using labels instead of using the picker-driven metadata we used before, we should probably investigate getting rid of the old picker code (at least as it pertains to the dates and trials). Let me know if I can help on this at all!

**Comment by jafeltra** [comment]
Good call. I'll look into that!

**Comment by jafeltra** [comment]
[JA2] #reason shows up as complete before you choose a value

**Comment by jafeltra** [comment]
JA2 should be set. Still looking into Dylan's comment.

**Comment by jafeltra** [comment]
@Dtphelan1 I believe your comment should be addressed now. I removed the string trigger "#date" and "#title" since those triggers were essentially used as labels, which we now have for those shortcuts. I also got rid of the `picker` attribute in shortcut metadata. It wasn't used to trigger portals anymore and had all the same information as stringTriggers in the metadata.

There could be cases I missed in testing, so if you find anything while testing different shortcuts, let me know.

**Comment by jafeltra** [comment]
[JA3] Closing and reopening a note with #disease status #as of #date breaks because the date format is now "D MMM YYYY" and it tries to parse a number rather than a date.

**Comment by jafeltra** [comment]
[JA3] should be set now!

**Comment by jafeltra** [comment]
@Dtphelan1 this should be ready for a re-review now!

**Comment by jafeltra** [comment]
Removed myself as a reviewer of this PR since I've made a decent number of changes. This needs a second reviewer now.

**Comment by Dtphelan1** [comment]
Truly impressive work here @jafeltra and @sgober. Removing Pickers really simplifies our approach to shortcut metadata and brings damn tears to my eyes. I'm testing things functionally, but the code looks great.

**Comment by sgober** [comment]
I'll take over the second review on this PR since @jafeltra made enough changes to what I originally did. hope that's cool

**Comment by sgober** [comment]
Turns out I can't approve my own PR, but I approve this!  If everyone else thinks my approval is okay I can go ahead and merge.

**Comment by jafeltra** [comment]
I'm good with it! I'll merge now!

**Pull request merged**
