### PR TITLE
Storing Longitudinal Data Table Favorites Locally via Preference Manager

### PR DESCRIPTION
**Pull request by ashih2018**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

Used preference manager such that longitudinal table can store favorites within local storage. Thus when you refresh the page after selecting lab/vital names as favorites, they will be favorited and show up as favorites on load, starred in sorted order.
## Submitter:

**Running the Application**

- [X] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Two small comments: 
1. We might be able to avoid a second loop in the formatData function by adding elements to the favsArray and notFavsArray based on the result of `_.includes`. 
2. We should be able to avoid the use of `let` in defining Arrays. 

Once those two things are addressed I'll give this another look, but on the whole this looks great! Good work!

**Comment by Dtphelan1** [comment]
Nitpicking a little bit - the code for initializing the favorites is a littlle redundant. Could we do something more akin to this: 
```
const curData = {
    name: section[conditionIndex].name,
    unit: section[conditionIndex].data_cache[0].unit,
    datesAndData: this.buildDataObject(conditionIndex, section),
    bands: section[conditionIndex].bands && section[conditionIndex].bands.length > 0 ? section[conditionIndex].bands : null,
    favorite: _.includes(favorites, section[conditionIndex].name,
}

if (curData.favorite) { 
    // push onto favs
} else { 
    // push onto notFavs
}
```

Also, can we name the original favorites array something a little more descriptive, like favoritesNames or something? Just bevauyse there are two arrays of favorite data

**Comment by mgramigna** [comment]
I agree with Dylan's comments. We should try to avoid unnecessary looping if there is a reasonable other solution. This looks good to me though!

One nit pick is that now that `<LongitudinalTable` is starting to get a lot of props, let's put each prop on its own line to make everything a little easier to read. Here is an example of this: 
image

**Comment by ashih2018** [comment]
Matt and Dylan I implemented both of your suggestions!

**Comment by Dtphelan1** [comment]
I think this looks good! Works as expected, addresses everything I noticed and overall looks great!

**Comment by Dtphelan1** [comment]
I'm good with this!

**Comment by ashih2018** [comment]
@mgramigna resolved!

**Comment by Dtphelan1** [comment]
[DP1] Look like we need to run `yarn lint` on this before it will pass travis.

**Pull request merged**
