### PR TITLE
Improve open note matching

### PR DESCRIPTION
**Pull request by mgramigna**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

For Jira 1453. With Fuse.js, the searching of open note content was behaving strangely. I changed it to use lunrjs now, and the behavior seems to be more like what you would expect.

Compare with searching open note content on fluxnotes.org, e.g. Search for "Stable" or "Disease Status" and this will highlight some of the improvements for this PR.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
I noticed that when searching an open note, the search results still show the hashtag for the shortcut even though it's no longer displayed in the editor. Since it's not related to this PR, should we just make a jira to make the search result consistent with the content of the note?
image

**Comment by nicoleng12** [comment]
[NN1] - This is small, but can we add lunrjs to the list of third party libraries in our wiki? https://github.com/FluxNotes/flux/wiki/About-Flux-Notes

**Comment by mgramigna** [comment]
Resvoled NN1, good catch Nicole. I'm going to check to see if your first comment is something trivial to change and if not then a Jira probably makes sense

**Comment by nicoleng12** [comment]
Overall this looks good! 

[NN2] - I noticed that you have to type the whole word in order for the search to find it in the open note. For example if the note contains toxicity, I have to write "toxicity" for the search to display the open note as a result. I would expect it to start including the open note as a search result when I type "tox" at least.

**Comment by mgramigna** [comment]
Removed hashtags from search results

**Comment by mgramigna** [comment]
Addressed NN2

**Comment by danlee1025** [comment]
image

[DL1]  The second search results seems to highlight a lot of information irrelevant to the query.  I'm guessing it matched because of `tumor` but it probably shouldn't highlight the text beyond that.  What do you think of that behavior?

**Comment by danlee1025** [comment]
image


[DL2] The 1st search result seems weird that it would match and it seems to match twice on the title of the open note.

**Comment by mgramigna** [comment]
DL2 resolved. Investigating DL1

**Comment by mgramigna** [comment]
Important update: after talking with Greg, it seems like the actual best approach for this is just using a regex. So I switched to that. Now I think it behaves how a clinician would expect it to which is the ultimate goal

**Comment by mgramigna** [comment]
rebased

**Comment by danlee1025** [comment]
[DL3]  When I open the 1st note and search for `abdomin` the correct search results show up, but when I search for `abdomina` there are no more search results.  Then when I search for `abdominal` the search results appear again.  Another example is `toxic` -> `toxici` -> `toxicity`.

image

image

**Comment by mgramigna** [comment]
DL3 is a result of elasticlunr tokenizing the strings weirdly. Looking into it to see if there's an easy solution but if not I think it might warrant a Jira since it's unrelated to open note matching

**Comment by mgramigna** [comment]
Made a Jira for DL3

**Comment by nicoleng12** [comment]
Looks good! Nice job Matt!

**Pull request merged**
