### PR TITLE
Medications via SMART on FHIR

### PR DESCRIPTION
**Pull request by dehall**
Addresses ASCODCP-1868.

Fixes a number of issues related to getting and displaying Medications when fetching a patient via SMART on FHIR:

1. FHIR `MedicationOrder` fields `reasonReference`, `medicationCodeableConcept`, and `dateWritten`  are manually mapped in `MedicationRequested.fromFHIR`. `reasonReference` and `medicationCodeableConcept` seem to be a spec or other toolchain issue as they are not even included in the profile that gets passed to the ES6 exporter. `MedicationRequested.StatementDateTime` (mapped from FHIR `MedicationOrder.dateWritten`) is not part of mCODE 0.5, but is used in newer versions of the spec, so I borrowed from those future versions to get that data loaded.
2. Adds a workaround in `Reason.fromFHIR` to specifically handle the types of values that class can have. This should be fixed permanently in the es6 exporter to address https://github.com/standardhealth/shr-es6-export/issues/35
3. Fixes some issues with references and IDs in the fromFHIR logic
4. The UI for Medications checks for prescription date in the field FluxMedicationRequested.expectedPerformanceTime, but the test patients don't have data that maps into this field. Synthea patients instead have a field MedicationOrder.dateWritten (which is required by the argonaut profile). Leveraged the existing FluxMedicationRequested.startDate field to check for dateWritten as a fallback, and updated places that called expectedPerformanceTime.timePeriodStart
5. Fixes for "null" displaying in the UI when certain fields such as dosage are missing

To test this:
 - Launch the Compass app via http://moonshot-dev.mitre.org:4001/?auth_error=&fhir_version_1=r2&fhir_version_2=r2&iss=&launch_ehr=1&launch_url=http%3A%2F%2Flocalhost%3A3000%2Flaunchcompass&patient=&prov_skip_auth=1&provider=&pt_skip_auth=1&public_key=&sb=&sde=&sim_ehr=0&token_lifetime=15&user_pt= -- make sure that FHIR Version is set to R2 (DSTU2) and the launch URL points to your local env /launchcompass
- Select any provider and then one of the patients with last name McOde123 (not Marvin or Matthias - they don't seem to have a cancer condition, which I'm very confused about)
 - When Compass loads, switch to the cancer condition.
 - Verify the medications load correctly.
Note that the synthea patients used here have minimal data in their medications so looking for alternative sources of data would be ideal. 

Known limitations:
 - There seems to be an issue with displaying Medications in general for non-cancer conditions. See jira ASCODCP-1893 for more info. This PR only addresses displaying Medications for cancer conditions.
 - There seem to be a lot of places where null pointer errors could theoretically occur, based on data. I took the approach of only updating things where I actually saw errors, but if people want I can revisit that.
 - Dates are formatted as FHIR dateTime strings, which look like "2018-07-24T20:01:41-04:00". Rather than address those piecemeal here I think that should be a separate task to handle all places where dates are processed and displayed to ensure consistency. See Jira ASCODCP-1857

---
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- **N/A** Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- **N/A** Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- **N/A** Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- **N/A** Document any new APIs/extension points
- **N/A** Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by danlee1025** [comment]
[DL1]  Looks like the timing for `loperamide` on `/pilot1` got lost in the changes.  It is now showing as missing data.  Screenshot below of what should be displayed on `master`.
image

**Comment by danlee1025** [comment]
I'm assuming it has to do with the changes to the `transformMedicationsToColumns` function in `VisualizerManager.jsx`.

**Comment by mgramigna** [comment]
Just chiming in on DL1, that medication is the only one that uses `doseInstructionsText` instead of `timingOfDoses`.

We default to `timingOfDoses` for the medications, but if this is undefined, as is the case for this med, we use `doseInstructionsText`. Not sure if this is helpful information or not but there it is.

**Comment by dehall** [comment]
Good call, the original changes unintentionally dropped the use of `doseInstructionsText`. Addressed DL1 in latest commit

**Comment by rdingwell** [comment]
For any of the changes made in the shr classes are those going to need to be re-implemented when updated to mcode 0.9?

**Comment by dehall** [comment]
In a perfect world no but realistically yes. With the exception of the `dateWritten` piece which comes from a more recent version of mCODE, all the other changes are things that are part of the spec but bugs are preventing them from showing up, or otherwise known limitations of the es6 generator. We could try to fix those bugs and limitations but the workarounds require a lot less effort, and hopefully we don't have to regenerate the classes too many times.

**Comment by Dtphelan1** [comment]
[DP1 - Comment]/Open Question Because there are number of resources we currently don't support, the console gets barraged with >300 errors on the initial load. Is there a more graceful way we could/should want to handle this?

**Comment by Dtphelan1** [comment]
After looking at the post-processed FHIR JSON, I've confirmed that there are no other medicationRequested objects that we've failed to pull into our code. I'll do another quick scan over the files, but I'm feeling good about this.

**Comment by dehall** [comment]
Re: DP1 -- I agree, that's a good idea. I hadn't given it much thought originally but now that I do think about it it would be pretty easy to 1) add a configuration setting to only fetch resource types we care about and/or 2) turn off or greatly reduce the error messages that only show up because the FHIR doesn't have profiles. IMO that should be a separate Jira but if you feel strongly I could address option 2 here.

**Comment by Dtphelan1** [comment]
I'm good with a second JIRA that would also allow us the time to consider option 1 as an avenue. Could you make that JIRA?

**Comment by dehall** [comment]
Created ASCODCP-1934

**Pull request merged**
