### PR TITLE
Get help portal expand option

### PR DESCRIPTION
**Pull request by sgober**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

JIRA 1927 (mockups are linked here)

Supports initial get help menu with default options expand and open GUI (currently hooked up to methods that log that they are clicked).  There should be minimal effort in this component to set up custom get help options.  Since this behaves differently than our other list menu, test out the behavior of the menu and see if anything behaves in a way you wouldn't expect.

Some discussion needs to be had about how to deal with the new subtype method for shortcuts and how to incorporate this into getting the completion component.  For now, I have it based on the type.  Also, the get help menu shows even if the the shortcut is incomplete.  Based on a discussion with @Dtphelan1, it might make sense to have other get help options when the shortcut is complete and grey out options as needed.

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] - remove "open GUI" option from default

**Comment by sgober** [comment]
[SO1] add menu subtype

**Comment by gregquinn2001** [comment]
[GQ1] When I choose expand it does write to but twice. There's also a "here" log message as well which can be deleted I'm guessing

**Comment by gregquinn2001** [comment]
[GQ2] When I down arrrow to select Get Help then expand and then hit enter, I get the console logs but I also get a new line added to the editor so I think the Enter key press is being used by the portal to cause selection in the menu but also being used in the editor.

**Comment by sgober** [comment]
DP1 and SO1 (I think) resolved

I added subtype menu to:
#disease status
#toxicity 
#staging 
#enrollment 
#as of
#reference date
#to 

@Dtphelan1 @gregquinn2001 are there any others I'm missing?

**Comment by gregquinn2001** [comment]
> DP1 and SO1 (I think) resolved
> 
> I added subtype menu to:
> #disease status
> #toxicity
> #staging
> #enrollment
> #as of
> #reference date
> #to
> 
> @Dtphelan1 @gregquinn2001 are there any others I'm missing?

I guess these should be included as well:
#unenrolled (UpdaterBase)
#deceased (CreatorBase)
#ER (SingleHashtagKeyword)
#PR (SingleHashtagKeyword)
#HER2 (SingleHashtagKeyword)
#stop medication (CreatorBase)
#reduce medication (CreatorBase)

**Comment by sgober** [comment]
now SO1 is resolved

**Comment by Dtphelan1** [comment]
re: GQ2, the way of shortcircuiting the onKeydown handler is to return a valid editor state. We should do this whenever the onEnter is triggered, since we always want that to simply close the portal and end execution. 
[DP2] - Why does selectedIndex not actually reflect the index? On line 76 we subtract 1 from the index before using it as an index? That doesn't sound right... refering to - `this.state.selectedIndex-1`
[DP3] - I'm not sure we should be using the `initiatingTrigger` to get the text display for the shortcut in the getHelp list item. @gregquinn2001 is there a better getter on Shortcut's that we should use here? Or is this what we should be using?
[DP4] - Can we use either our typical block-style if-else format, or a ternary operator to determine iconClass in our render of ContextGetHelp.
[DP5] - Our menus for other components overflow and wrap back around if you arrow down at the end of the list. Can we be consistent with this behavior in this menu as well?

**Comment by gregquinn2001** [comment]
Please stop adding me as a reviewer to pull requests! If I can be a full reviewer, I will add myself! I'm doing some review but I'm not doing a thorough review of every pull request. This still needs two other reviewers.

**Comment by gregquinn2001** [comment]
For DP3, I think we should be calling getDisplayText() to determine what to display for a shortcut.

**Comment by sgober** [comment]
@Dtphelan1 @gregquinn2001:
GQ1, DP3, DP4 and DP5 resolved.  See below comment on DP2.  Will investigate GQ2 tomorrow.

Some comments:
[DP2] The `this.state.getHelpOptions` is all the options that fall below the dividing line, so in this case it would just be expand.  In the future we can use this state variable to hold custom options for the get help menu (see the `renderOptions` for how this is used.  However since the get help option in the first part is a part of the menu, it is counted in the selectedIndex value, but not in the getHelpOptions as I described above.  Therefore there is an off by one when translating the selectedIndex to getHelpOptions, so the -1 accounts for that.  If you can think of a cleaner way to do it let me know
[DP3] Modified this but am still stripping out the #.  If we want to keep the hashtag it'll be easy to add that back in
[DP5] I have it wrapping so that if you down key the last option in the list it selects the get help option in the first slot.  Is this the intended behavior?

**Comment by Dtphelan1** [comment]
I explained what the root cause off GQ2 was in my earlier comment. Start by looking into programatically returning State in that handler

**Comment by Dtphelan1** [comment]
Re: DP2, could we at least use a comment to explain why we're subtracting one from the index? That will help improve clarity. 
Re: DP5, I think that's how all our other menus work, so I'm good with it for now.

**Comment by sgober** [comment]
DP2 and GQ2 resolved!  this is now ready for another review.

**Comment by Dtphelan1** [comment]
[GQ2/DP6] - We still have console logs in the onEnter case - it's defined in the `expand` function. 
[DP7] - The onClick handler for the "getHelp with..." doesn't really do anything. Could we remove it if it's not doing anything?
[DP8] - In all places where we're messing with index values, can we comment accordingly? Specifically I'm thinking of renderOptions, but if there are others they too should be included.

**Comment by sgober** [comment]
Resolved DP7 and DP8.

[GQ2/DP6]  I left it in there so the person that is doing the expand task has a point of reference.  I can certainly remove it though.

**Comment by Dtphelan1** [comment]
I'm indifferent re: the log, just wanted to make sure we we're either intentionally leaving it in there or removing it.

**Comment by sgober** [comment]
Re @Dtphelan1: doesn't matter to me, someone make a decision! Also rebased so this should be good for a re-review/second review

**Pull request merged**
