### PR TITLE
Blur search field on click

### PR DESCRIPTION
**Pull request by gregquinn2001**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

JIRA 1386. blur search field after selecting search result.

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [ ] Existing tests passed

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by mgramigna** [comment]
[MG1] I'm getting a console error when I click on a result as opposed to selecting it with the arrow keys/enter key

**Comment by gregquinn2001** [comment]
rebased

**Comment by jafeltra** [comment]
I reviewed this and didn't notice anything besides the error Matt pointed out!

**Comment by mgramigna** [comment]
Fixed [MG1] with Greg

**Comment by gregquinn2001** [comment]
rebased

**Comment by jafeltra** [comment]
Looks good!

**Pull request merged**
