### PR TITLE
JSON Date Changer Utility

### PR DESCRIPTION
**Pull request by danlee1025**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Addresses JIRA-1152.

-  Added node application to change all dates in patient JSON.
-  App accepts two args:
    -  `path-to-patient-json`: input JSON file, app expects this to be an array for SHR entries.
    -  `encounter-entryid`: entry id of encounter to calculate difference to add to all dates in JSON file. 
-  App will calculate the difference between the current date and encounter date and add that duration to all dates.
-  App will overwrite patient json file and create a backup in the same directory.
-  Added README file with example on how to run the app.

Potential shortcomings:
-  All dates of each entry are changed, but note content dates remain the same.  Should I create a JIRA for this?
-  Currently the app is placed in `src/lib/json-date-utility`.  I wasn't exactly sure where to place this so let me know if there is a better place for this.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

-  Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added Enzyme-UI tests for slim mode 
-  Added Enzyme-UI tests for full mode
-  Added backend tests for new functionality added
-  Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
This looks really good Dan. Nice job! Good, clear documentation. I followed the steps and everything worked. The patient json dates were updated and a backup file was created. In the targeted data panel I can an updated visit reason. I tested against the demo script and it works. Backend tests work. I tested this in chrome in IE and it all works

**Comment by gregquinn2001** [comment]
[GQ1] I would model it after noteparser as it is also a separate command-line utility that we run via yarn (yarn parse). It exists in the noteparser folder including an app.js. If you don't like that, let's discuss moving noteparser (app.js part at least) to lib as well?

**Comment by gregquinn2001** [comment]
[GQ2] Can we add a script to package.json to run it like we have for parse so we don't have to worry about paths. something like yarn json-date-update < filename> < entry id of encounter >

that way I can run this from the root directory where we run other yarn commands typically (at least I do. if others don't, let me know)

**Comment by gregquinn2001** [comment]
This is awesome though! It will make demos much nicer too!

**Comment by gregquinn2001** [comment]
[GQ3] Not sure what people think, but our root readme actually has yarn parse instructions in it. I'm thinking we should add it for the json-date-update OR patient-date-update? We don't want the content in 2 places though so I guess we'd have the README in the subfolder reference the root readme then?

**Comment by gregquinn2001** [comment]
Let's create a JIRA to make the utility use the data access layer such that a patient on a server could be retrieved and updated??? That seems like it could be very useful. Of course, then we'd have to support update in hard code patient json data source.... need to think through this a little more...

**Comment by danlee1025** [comment]
Addressed GQ1, GQ2, and GQ3.  

For GQ3, I added instructions in the root README and removed the README in the patient-date-updater directory since noteparser doesn't have its own README.

**Comment by Dtphelan1** [comment]
@gregquinn2001  is this branch waiting for any further review?

**Pull request merged**
