### PR TITLE
Highlight open note search results

### PR DESCRIPTION
**Pull request by mgramigna**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

For Jira 1446, highlighting the open note search results in the editor. When the search results appear for an open clinical note, the matching text is highlighted in the note. This works for structured data or plaintext. For structured data, the entire text is highlighted but for plaintext only the matching part is highlighted.

One potential shortcoming is that the highlights go away when the user clicks away from the search. However the important thing is that they can still scroll through the highlighted results when the search bar is open

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added Enzyme-UI tests for slim mode 
- [ ] Added Enzyme-UI tests for full mode
- [ ] Added backend tests for new functionality added
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
[JA1] I accidentally typed "57\" into the search and got the following error in the console: 

[JA2] I have the most recent note open on /pilot1 and tried searching for "months" which is the last word in the note, and it doesn't get highlighted, but it is in the results list.

[JA3] This can be a separate Jira, but searching for text that is plain text and structured data doesn't highlight anything (ex: "is a 57").

**Comment by mgramigna** [comment]
Resolved JA1

**Comment by mgramigna** [comment]
Resolved JA2

**Comment by jafeltra** [comment]
JA1 looks good! For JA2, 'months' now gets highlighted, but if it's off screen, it doesn't scroll for me. I'm not sure if that's related at all.

**Comment by mgramigna** [comment]
Fixed the scrolling problem of JA2

**Comment by nicoleng12** [comment]
This looks really good! The highlighting of open note search results is a really nice feature. This looks good in IE and in chrome.

[NN1] - Currently you the highlight doesn't show up when you search for 2 structured phrases. For example, open the first note in the list and then in the search type "disease status complete response". I would expect both "disease status" and "complete response" to be highlighted in the note since the search results bolds both in the results. The rest of the search functionality looks good though and I don't think this issue should prevent this PR from getting merged if it's not an easy fix. This can be made into a separate jira.

**Comment by mgramigna** [comment]
NN1 and JA3 relate to the same issue: How to handle multi-word search queries that involve words that match structured data. I think it can be encapsulated in one Jira

**Comment by mgramigna** [comment]
I made a Jira for NN1/JA3

**Comment by jafeltra** [comment]
[JA4] Not all the proptypes seem to be updated. This will also need to be rebased.

**Comment by mgramigna** [comment]
Rebased and resolved JA4

**Comment by nicoleng12** [comment]
This looks good! works in chrome and IE

**Comment by mgramigna** [comment]
I made the proptypes not required because otherwise it broke the CCP app

**Comment by jafeltra** [comment]
Looks good to me! Nice job!

**Pull request merged**
