### PR TITLE
[ccp] Add tnm to filter options

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Pulls TNM info from the patient record to display as a filter.  The test data doesn't have TNM info so the
filters won't do anything, and if the filters would likely have to be changed when the data is present since its location and key name might be different when obtained from the data source.

I was considering making a separate section for "staging" instead of pathology, but decided against it.  I was also considering whether it would be a good idea to allow for nesting filter options.  The pathology section holds a lot of the filters, but could probably be subdivided with subheaders like "tumor markers" and "staging".  

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [ ] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Looks good, but weren't the TumorMarkers fixed by Rob's PR? I'm going to remove those changes from this and then approve.

**Comment by Dtphelan1** [comment]
One last thing I want to confirm before approving and merging is whether or not we wanted to add fields to our mock data to allow those filters to produce non-empty lists of comparedData. It took me a minute to convince myself that the filters were actually working and that the problem was that the data just doesn't have any TNM or Stage values for any patients.

**Comment by rdingwell** [comment]
@Dtphelan1 yes, I think we should add some fields to the existing test data so we can show it working.  
@KeeyanGhoreshi  Please add some fields to the data in src/mcode-pilot/mock-data/ mock-data.js for the TMN information.   The larger set of data we have has this information nested under diseaseStatus like so, so please adjust where the filter is looking for this information as well.  

`"tmn" : {
				"t" : " T1b",
				"n" : " N0",
				"m" : " M0"
			},`

**Comment by KeeyanGhoreshi** [comment]
I've added TNM info to the mock data, as well as some other things.  I moved the transformed data out of the javascript file into `json` so I could easily write to it and wrote a script that will automatically add fields to the mock data with random values.  The script ignores fields that are already present in the data.  

In order to add the TNM information to the mock data, all I had to do was add some weighed values to the `transformedDataModel` and run the script.  I also added the other categories to the model, so it could potentially generate data (or fill missing info).  But for this PR I just used it to add TNM staging info to the `diseaseStatus` section of every patient.  

There's some oddities in the formatting that I would consider changing if others had a problem with it, namely the separation of weight/value pairs into two arrays that reference each other by index, and the usage of `!` to denote a default value.  

Of course, the script is totally superfluous, all that really matters is that the TNM staging info is added to the data.  But the script can be used in the future to add more fields to the mock data, so I pushed it up anyway.  The script is a bit limited since it doesn't take into account relationships between fields., and can only really provide a random dice roll for any value.

**Comment by Dtphelan1** [comment]
[DP1] Can we add instructions for using the new script you wrote to the README?

**Comment by Dtphelan1** [comment]
[DP1] - Doesn't look like the space gets added when there's nothing but plaintext in the editor. To replicate: 
1. Create new note.
2. Type "anything".
3. Insert @patient with no space.

**Comment by Dtphelan1** [comment]
Just a reminder that once those intructions are put in the README we can merge this and get moving.

**Comment by Dtphelan1** [comment]
Needs a rebase, but after that I think this will be good.

**Comment by sgober** [comment]
rebased and looks good

**Pull request merged**
