### PR TITLE
Clinical trial matching fits full width of tdp

### PR DESCRIPTION
**Pull request by Dtphelan1**
👀👀👀Don't mind me, just pushing up a little something small that came out of the pre-grooming. 😄

### CODE REVIEW

**Comment by jafeltra** [comment]
Umm I really want to approve this, but the code doesn't compile :(

**Comment by jafeltra** [comment]
So I looked at this a bit, and I'm not actually sure we want to do this anymore. We've made changes since that Jira was made, and all the other tables that have only one column don't take up the full width anymore. I don't think we necessarily want Clinical Trials to be the only one that takes up the full width. Since Dylan is on vacation, I'm going to close this for now, and we can reopen later.

**Comment by Dtphelan1** [comment]
My heart is shattered and my spirit is broken.   
  

  
  

  
  
>

**Comment by jafeltra** [comment]
I was afraid of this outcome. I will not recover.

**Comment by mgramigna** [comment]
Any update on this?

**Comment by Dtphelan1** [comment]
Yes, I am working on it. Stay tuned.   
  
  
  
  
  
    
  

  
  
>

**Comment by Dtphelan1** [comment]
hoping it will be done by the time i return from break. will reach out if i need any assistance.   
  
  
  
    
  

  
  
>

**Comment by mgramigna** [comment]
Thanks. Looping in @sgober

**Pull request closed without merging**
