### PR TITLE
Ccp mcode tests

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Wrote tests for most of the components and functions, there are some missing but they have questionable testability.  There are tests for the reducers and actions as well as some of the components, though some of the components do not lend themselves to easy testing since the logic is contained within the render function.  There are a couple of changes that could be made to the main code to move things into functions that can be easily unit tested.  

Some of the tests are kind of flimsy and use class names to identify components (as well as counting the number of divs/spans to determine if the components were rendered at all, and if the correct number were rendered.  This is prone to being broken with changes to class names or addition of extra divs/spans to the rendered html.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [x] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Before I go ahead and review fully, Keeyan were there other sub-procedures that needed to be broken out from some of the larger render functions?

**Comment by Dtphelan1** [comment]
[DP1] Test is written so that it is only compatible with mac/unix OS; when defining the `test-mcode` command you should follow the motif that `test-fullapp` and `test-ui` establish -- the root script just calls `run-script-os`, and from there we define OS specific commands that allow the setting of the CI variable in an OS-appropriate way.

**Comment by Dtphelan1** [comment]
Resolved DP1. If I can confirm that tests still run on mac then we're gucci.

**Comment by sgober** [comment]
`yarn test-mcode:darwin:linux` and `yarn test-backend:darwin:linux` work for me on mac! my approval still stands

**Comment by Dtphelan1** [comment]
So the way the script works we should be able to just run yarn test-mcode and it should branch to those based on an query to the machine re: the running OS. Lokos liek the version of this tool, `run-script-os` that we're using is problematic on macs but hopefully an upgrade to the package should fix things. Julia is looking into this with me.

**Comment by Dtphelan1** [comment]
Version upgrade should fix this -- confirmed with julia and pushing changes once I confirm it doesn't break windows!

**Pull request merged**
