### PR TITLE
Style alignment

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Some small changes to the styling of the ccp components.  This is mostly changes to the colors of the components.  My main focus was keeping the ccp table looking as close to possible as the original while using the colors defined in `_variables`. This meant using some of the grays and blues out of the context which they're defined in `_variables`, so if that might be a problem, the grays and blues for the table should probably be broken out into their own variables.  For example, we might not want a recoloring of the underline for fluxnotes text to affect the color of the `select all` buttons background.  

Most of the inline styling is removed as well, so that the table and legend both pull colors from the `_variables` file.  This did require the addition of a couple of new green and red colors.  

There's some other minor changes to fix some spacing and other html/javascript styling.  

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
@KeeyanGhoreshi, did you test the other endpoints to make sure you didn't change the other apps by changing styles?

**Comment by KeeyanGhoreshi** [comment]
I took a look and it doesn't seem like anything is different.  There shouldn't be any changes in this PR that affect any other endpoints, since only the ccp component files were updated, and the `_variables` file only had new colors added for the ccp table, all the existing colors are untouched.

**Comment by Dtphelan1** [comment]
I've got a question on styling the nested ternaries that I'll ask in person, but after that I'll finish reviewing. 👍

**Comment by Dtphelan1** [comment]
[DP1] Looks like increase and decrease styling is flipped. 

image

**Comment by KeeyanGhoreshi** [comment]
[DP1] Should be addressed, just a small `true/false` mixup.

**Comment by Dtphelan1** [comment]
This looks good to me.

**Comment by mgramigna** [comment]
Looks good Needs one more rebase and I will approve

**Pull request merged**
