### PR TITLE
[CCP] Fixes side effect header bug when side effect no longer exists

### PR DESCRIPTION
**Pull request by noranda**
This PR satisfies [JIRA 2116](https://jira.mitre.org/browse/ASCODCP-2116) which fixes a bug where the side effect header name would disappear when switching to a filter that removes all side effects of that type. For example, selecting the `erectile dysfunction` side effect filter and then selecting the `gender` demographic similar patients filter would remove the side effect filter from the list and render an empty string in its place.

To fix this, `sideEffects` and `selectedSideEffects` were moved from the component level state into redux and then checked on `UPDATE_PATIENT_OUTCOMES`. If after patient outcomes were updated the selected side effect filter no longer exists, it now reverts it back to `Most Common`.

As part of the refactor, moved `gatherSideEffects` to its own util to prevent unnecessary function calls on every render and to use in the reducer.

Tests were also fixed. Due to the mutating behavior of `sort()`, the `similarPatientTreatmentsData` array in the tests would result in an inconsistent order. The array was duplicated on initialization to prevent this.

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [ ] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by dehall** [comment]
[DH1] I stumbled upon this completely by accident but there's a new bug with the checkboxes. Check the top-level option for either the "demographic" or "pathology" section, collapse the section, then re-expand it and uncheck the top-level option. The options become de-selected based on the number of patients returned, but the checkboxes still display as checked. If you click on them once in this state it doesn't appear to do anything but is actually enabling them, then if you click it again it disables and everything is back to normal. If this is the only way to trigger weirdness, it's not a big deal, but I'm concerned there may be other related bugs. I'm not able to reproduce this on fluxnotes.org

**Comment by KeeyanGhoreshi** [comment]
DH1 exists on master as well.

**Comment by dehall** [comment]
So this looks good but I have to wonder, would it be a significant effort to display 0% if the selected side effect no longer exists in the cohort? The current approach feels a little jarring when you change something and then suddenly the side effects change because the previously selected side effect isn't present anymore.

**Comment by noranda** [comment]
@dehall I had initially thought to implement this as you suggest, showing 0% down the table with the selected side effect, but decided against it because the list of side effects is dynamically generated based on the data. If I included the selected side effect that no longer exists, why not then show all possible side effects even though they also don't exist? In order to avoid that rabbit hole, I decided to reset the list anytime the side effect no longer appeared in the data. I agree the sudden change could be a bit distracting, however it is consistent with how the rest of the data in the table also updates to show the current data given the selections.

I rebased this branch and cleaned up some code.

**Pull request merged**
