### PR TITLE
Fix multiple open portals

### PR DESCRIPTION
**Pull request by karenzheung**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

JIRA 2060 
Fixes both suggestion portal and completion portal opening at same time

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [x] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ N/A] Document any new APIs/extension points
- [ N/A] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [X] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [X] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by karenzheung** [comment]
there aren't actually 55 files changed. I'm trying to figure why it says that

**Comment by danlee1025** [comment]
do you need to rebase with `shortcut-entry-overhaul`?

**Comment by karenzheung** [comment]
I ran `git rebase shortcut-entry-overhaul` and it says my current branch is up to date

**Comment by sgober** [comment]
I'm seeing it needs a rebase

**Comment by danlee1025** [comment]
Can you checkout to your local `shortcut-entry-overhaul` and run these commands:

- `git fetch -a`
- `git reset --hard origin/shortcut-entry-overhaul`

And then try the rebase again.

**Comment by karenzheung** [comment]
Thank you! That worked perfectly!

**Comment by sgober** [comment]
[SO1] When I do @condition, then escape and arrow back, when I arrow forward the patient header shifts a couple of pixels to the left.  I feel like this should remain fixed

[SO2] In order to get the condition portal to pop up I have to arrow to the right twice.  This doesn't seem optimal if we can just have it work with one arrow to the right, but if that is too difficult then I am okay with it as is

This will also need another rebase

**Comment by karenzheung** [comment]
I now realize that the suggestion portal is still opening but it's rendering kind of off screen. If you scroll down when the patient header shifts you'll see the portal at the bottom. Looking into it now

**Comment by sgober** [comment]
This looks great @karenzheung!  It works for @condition, @procedure and @medication.  My only complaint is you have to hit the right arrow twice to get the portal to pop up.  If we could do it in one, I think that would be idea, but if people are okay with it being two I will approve this!

**Comment by karenzheung** [comment]
@sgober There was a previous task a while ago to fix the disappearing cursor when you arrow key into a structured field at the start of the paragraph. The result is the double right arrow key to get to the end. I think it was an issue with a zero width node but I don't recall the exact details. I can look into it until I get input from other reviewer

**Comment by karenzheung** [comment]
Added fix so you only need to right arrow once at structured field at the start of paragraph

**Comment by sgober** [comment]
Needs a quick yarn lint and rebase, but this works great!  Nice job @karenzheung!

**Comment by karenzheung** [comment]
rebased and linted

**Comment by danlee1025** [comment]
Looks good!

**Pull request merged**
