### PR TITLE
Upgrade fhir-mapper to v3

### PR DESCRIPTION
**Pull request by dehall**
This PR just bumps the `fhir-mapper` dependency to v3.0.0 along with supporting code changes.
The big difference between fhir-mapper 2 and 3 is that v3 exports classes which can be instantiated with custom parameters, whereas v2 exported pre-instantiated objects.

For an example of how the customization can be used, make the following change to `dataSourceProps` in the `/smartcompass` section of `config.js`

```diff
         dataSource: 'GenericSmartOnFhirDstu2DataSource',
         shortcuts: [],
         dataSourceProps: {
-            mapper: 'CernerSandboxMapper',
+            mapper: 'SyntheaToV09',
+            mapperVariables: {
+                primaryCancerConditionCodes: ['444814009'] // you know what it is
+            },
             resourceTypes: ['Patient', 'Condition', 'Encounter', 'MedicationOrder', 'Observation', 'Procedure']
         },
     },
```

Then load from the moonshot-dev launcher patient "Janet238 Waelchi213". With the change in place the actual cancer condition (Malignant neoplasm of breast) will no longer be mapped as a `onco.core.PrimaryCancerCondition` but instead the Viral sinusitis conditions will get mapped as a cancer condition. The difference should be easily apparent since the UI only renders the basic metadata for non-cancer conditions, but all sections for cancer conditions. 

_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- **n/a** Branch implements task as expected
- **n/a** Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- **n/a** Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [ ] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Looks good all in all. Couple of nit-picky things: 
- Can we call the variable we pass to the constructor in CernerSandbox `mapperVariables` instead of just `variables`? We use that term elsewhere and the unity will probably help future debugging.
- Is there anywhere we can document in the Flux documentation/code a link to the fhir-mapper repo, so we have some link back to the documentation for what variables/mappers are and are not supported? I think we have a spot in the wiki for tools we use, and it would be helpful for me if we add a link there.

Other than those things I think I'm all set.

**Comment by dehall** [comment]
Added a line to https://github.com/FluxNotes/flux/wiki/About-Flux-Notes linking to fhir-mapper, will push code fix in just a moment

**Comment by Dtphelan1** [comment]
Actually - one more comment: Do we want to add a tag on the fhir-mapper repo for the new v3.0.0? We've done that with other tags, but I wasn't sure if we did it before publishing a new version and losing the old one, or if we did it defensively after we published a new version

**Comment by dehall** [comment]
I just tagged v3.0.0 now

**Pull request merged**
