### PR TITLE
Changing Modal Date Panel

### PR DESCRIPTION
**Pull request by jpa399**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

Added a control panel to the patient selecting modal to allow the user to change the day for which they are seeing the appointments.  The "today" button is white if the day being viewed is today's day and blue otherwise.
DON'T MERGE UNTIL MY OTHER PULL REQUEST, PATIENT-SELECTING, IS MERGED
## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [ ] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by jpa399** [comment]
[DR1] and [DR2] resolved!  Thanks so much!

**Comment by dreeves4321** [comment]
The active button styling still makes it look like a selected toggle to me, like it's currently on Today. If that's easily changed to the styling in the image above, that would be great. Otherwise, it'll do.

**Comment by jpa399** [comment]
I see what you're saying now, sorry I misunderstood that before.  Shouldn't be a problem!

**Comment by dreeves4321** [comment]
No worries! I wasn't clear enough.

**Comment by jpa399** [comment]
[DR2] now _actually_ resolved!

**Comment by sgober** [comment]
this now needs a rebase

**Comment by sgober** [comment]
this now needs a rebase

**Comment by jpa399** [comment]
rebased!

**Comment by jafeltra** [comment]
[JA2]: I noticed that the clinician's name doesn't seem to be displaying very well. Maybe if the `encounter.practitioner` doesn't exist we should say "last seen by unknown"? (See the picture)
image

**Comment by jafeltra** [comment]
[JA3]: I noticed the spacing in the patient control panel on `/pilot` was changed. I think this was actually introduced in the patient-selecting branch, but it might be easiest to just fix it in this PR, since it will hopefully be merged soon.

**Comment by jpa399** [comment]
[JA3] resolved!

**Comment by jpa399** [comment]
[JA1] resolved!

**Comment by jpa399** [comment]
[JA2] resolved!

**Comment by sgober** [comment]
[SO1] I'm not sure if there's a way around this, but if you are clicking the arrows and the amount of the appointments changes, you can accidentally click on something besides the arrows if you don't pay enough attention (I have a screen grab if you want to see). @dreeves4321 do you have any ideas?

[SO2] The modal reopens on the date it was on when it was last closed.  Is this the intended behavior?  I'm okay to leave it as is, it just throws me off when I open it and the date is not today.

**Comment by sgober** [comment]
[SO3] Travis is failing... not sure why, test and linting pass

**Comment by jafeltra** [comment]
For SO3 - Travis seems to just be struggling and not passing for a good reason. I think we're okay ignoring this now.

SO1 and SO2 are valid comments. I'm okay with leaving them both as is, but we might want @dreeves4321 's opinion on them. Dan, do you have any thoughts?

**Comment by dreeves4321** [comment]
For [SO1], I would fix the height of the modal. If there's overflow, then use a scrollbar. If not, then there's blank space. 
For [sO2], I agree, it should show today when open.
As an aside, I don't see any appointments. I must be missing a data file or it isn't local. So, unless I resolve that, my input will be pretty useless as we go forward with this component!

**Comment by jafeltra** [comment]
Thanks @dreeves4321! To get the appointments, you need to run the following two scripts: `yarn patient-date-update src/dataaccess/BreastMainTreatmentTry3Ella.json 100` and `yarn patient-date-update src/dataaccess/GistAdjuvantIhanos.json 100`. That should get you appointments for Ihanos and Ella today.

**Comment by jpa399** [comment]
[SO1] resolved!

**Comment by jpa399** [comment]
[SO2] resolved!

**Comment by sgober** [comment]
Related to SO1:  I am seeing that the modal can scroll when there are two appointments when it appears that there is enough room for them both without scrolling.

[SO3] The header does not stick when scrolling, only the x (exit button) does.  Can we make the whole header stay put when scrolling?

**Comment by jpa399** [comment]
[SO3] resolved!

**Comment by sgober** [comment]
It seems there is no background on the sticky header because the text is not readable after you scroll.  Also the x does move slightly on the scroll and should be fixed. 

Screen Shot 2019-07-22 at 4 04 42 PM

**Comment by jpa399** [comment]
Yeah just noticed there are still a few flaws, sorry about that.  I'll try to fix those.

**Comment by jpa399** [comment]
[SO1] and [SO3] should now be resolved I believe, thanks for the comments!

**Comment by sgober** [comment]
needs a quick yarn lint :)

**Comment by jpa399** [comment]
all set!

**Comment by sgober** [comment]
I have no idea why travis is failing... linting & tests pass and I was able to build this branch locally.  Anyone have thoughts or think I can go ahead and merge?

**Pull request merged**
