### PR TITLE
Convert to text function accepts fragments and state.document

### PR DESCRIPTION
**Pull request by karenzheung**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

## Submitter:
JIRA 1085
Copy and paste now works. 
Discovered a new bug where when copying text that includes structured fields slate will sometimes throw an exception. When slate doesn't throw an exception the copy will work. 
JIRA 1618 was created for this bug.

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [ ] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [ ] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Looks great at a first glance. Haven't fully tested yet but [DP1] - Can we remove that console log please 👍

**Comment by sgober** [comment]
This works great!  The one thing I noticed was that if you paste a structured phrase at the bottom of the view you cannot see the blue line.  I fixed this in one case and can look at it here if you want.  Otherwise looks good!

**Comment by karenzheung** [comment]
@sgober I forgot to rebase before. I just pushed with the branch rebased. Also the console tool should be closed when you test that specific case cause it adds an extra scrollbar.

**Comment by sgober** [comment]
@karenzheung my comment still stands (see photo).  I copied and pasted a structured phrase a few times and once I got to the point where the note was scrollable I saw that the line wasn't showing.  I'm pretty sure it's because when you press the enter button it doesn't scroll enough, so I'm not sure if there's a fix for this.
screen shot 2018-11-29 at 9 49 52 am

**Comment by sgober** [comment]
@karenzheung I will make a JIRA for this since it is unrelated.  Nice work!

**Pull request merged**
