### PR TITLE
initial implementation of click on shortcuts triggering components and shifting focus.

### PR DESCRIPTION
**Pull request by Dtphelan1**
Addresses 2171. Now clicking on a shortcut moves the cursor into an appropriate position.

### CODE REVIEW

**Comment by danlee1025** [comment]
Oops latest commit failed to compile.

**Comment by danlee1025** [comment]
Looks good.

[DL1]  Only thing I really notice is that it is not super consistent in opening up the completion component, especially when you're switching between 2 incomplete shortcuts.  

For example with `#disease status #status #reason`, switching between #status and #reason doesn't also open the completion component.  Not sure if it's something we want to fix in this PR or another JIRA.

**Comment by Dtphelan1** [comment]
No I think that's a fair comment. I can take a look at it later :)

**Comment by Dtphelan1** [comment]
Rebased this

**Comment by Dtphelan1** [comment]
I'm going to file the DL1 as under work to be done on the completion component, your original intuition @danlee1025 . While it is a weirdness that gets exposed more now, it's in a very different part of the code. I'm going to probably look at it next, but it shouldn't hold this up IMO.

**Comment by danlee1025** [comment]
Ok I'm going to do a quick re-review and approve this.

**Comment by sgober** [comment]
reviewing this now...

**Pull request merged**
