### PR TITLE
Placeholders

### PR DESCRIPTION
**Pull request by ashih2018**
_Pull requests into Flux require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:. Reviewers should complete every item on the bulleted list when reviewing._

HOW TO RUN: Go to flux wiki and go to pre release testing script. On terminal, run the scripts for ella and ihanos. On line 1628, change the time from 16:00 to 12:00 and the next patient button should work.

Saved placeholders between switching of patients.
Shortcomings:
- When switching between conditions (GIST and fracture for Ihanos), placeholders don't change.
- When switching from one patient to another, their placeholders do not save.
- When switching from one patient to another, if they have matching placeholders (e.g. disease status, toxicity), the placeholder status will be left on the previous patients placeholder. For example, if I fill in Status for Ihanos and go to the Rationale stage and then switch to Ella, her disease status placeholder will be at the Rationale stage rather than at the beginning stage(Status).

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome (primary browser for testing)
- [x] Manually tested in IE/Safari (verify app loads and basic feature testing)
- [x] Manually tested in Chrome in iPad mode (at minimum, viewing patient record)

**Task**

- [x] Branch implements task as expected
- [x] Key application features are updated as needed for task and tested (see: [Key Application Features](https://github.com/FluxNotes/flux/wiki/Key-Application-Features))
- [x] Task specific definition of done (as described in the Jira task) is met, if applicable.

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Pre release script is updated on the [Pre Release Testing Script wiki page](https://github.com/FluxNotes/flux/wiki/Pre-Release-Testing-Script) (add/remove single features to test, do not run through full script)
- [ ] Update the list of key features with new features on the [Key Application Features wiki page](https://github.com/FluxNotes/flux/wiki/Key-Application-Features)
- [ ] Document any new APIs/extension points
- [ ] Additional technical components and libraries are documented and added to [wiki](https://github.com/FluxNotes/flux/wiki/About-Flux-Notes) as needed

**Code Quality**

- [x] Code style guide is followed (see: [Code Style Guide](https://github.com/FluxNotes/flux/wiki/JavaScript-and-HTML-Code-Style-Guide))
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added backend tests for new functionality added

## Reviewers:

- Check that code is maintainable and reusable. Code reuses existing code and infrastructure where appropriate.
- Check the PR and code accomplishes the task's purpose.
- Check that new tests appropriately test the new code, including edge cases. Other existing tests pass.
- Verify Pull Request checklist is correctly completed by submitter.
- Try to break the code

### CODE REVIEW

**Comment by jpa399** [comment]
[JPA1] needs a rebase!

**Comment by jafeltra** [comment]
This looks good! It just needs a rebase, and then I will approve!

**Comment by sgober** [comment]
[SO1] When I click the next patient button to go to Ella, the header doesn't redraw so there is text overlapping (see below).  I don't know if this is a result of what @jpa399 did or if she can offer some insight, but this will need to be addressed at some point.  Not sure if that should be in this PR or have a separate JIRA.

**Comment by jafeltra** [comment]
Good eye Sarah! I definitely didn't notice that. I see it happening on master too, so I don't think fixing it should really hold this PR up.

**Pull request merged**
